/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	AboutMe:{
		documentInStages:{
			stages:"Stage"
		},
		company:{
			locales:"Locale"
		},
		links:{
			locales:"Locale"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		photo:{
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	AboutMeConnectInput:{
		where:"AboutMeWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	AboutMeCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		company:"CompanyCreateOneInlineInput",
		links:"AboutMelinksUnionCreateManyInlineInput",
		photo:"AssetCreateOneInlineInput"
	},
	AboutMeCreateManyInlineInput:{
		create:"AboutMeCreateInput",
		connect:"AboutMeWhereUniqueInput"
	},
	AboutMeCreateOneInlineInput:{
		create:"AboutMeCreateInput",
		connect:"AboutMeWhereUniqueInput"
	},
	AboutMeManyWhereInput:{
		AND:"AboutMeWhereInput",
		OR:"AboutMeWhereInput",
		NOT:"AboutMeWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		company:"CompanyWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		photo:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	AboutMeOrderByInput: "enum" as const,
	AboutMeUpdateInput:{
		company:"CompanyUpdateOneInlineInput",
		links:"AboutMelinksUnionUpdateManyInlineInput",
		photo:"AssetUpdateOneInlineInput"
	},
	AboutMeUpdateManyInlineInput:{
		create:"AboutMeCreateInput",
		connect:"AboutMeConnectInput",
		set:"AboutMeWhereUniqueInput",
		update:"AboutMeUpdateWithNestedWhereUniqueInput",
		upsert:"AboutMeUpsertWithNestedWhereUniqueInput",
		disconnect:"AboutMeWhereUniqueInput",
		delete:"AboutMeWhereUniqueInput"
	},
	AboutMeUpdateManyInput:{

	},
	AboutMeUpdateManyWithNestedWhereInput:{
		where:"AboutMeWhereInput",
		data:"AboutMeUpdateManyInput"
	},
	AboutMeUpdateOneInlineInput:{
		create:"AboutMeCreateInput",
		update:"AboutMeUpdateWithNestedWhereUniqueInput",
		upsert:"AboutMeUpsertWithNestedWhereUniqueInput",
		connect:"AboutMeWhereUniqueInput"
	},
	AboutMeUpdateWithNestedWhereUniqueInput:{
		where:"AboutMeWhereUniqueInput",
		data:"AboutMeUpdateInput"
	},
	AboutMeUpsertInput:{
		create:"AboutMeCreateInput",
		update:"AboutMeUpdateInput"
	},
	AboutMeUpsertWithNestedWhereUniqueInput:{
		where:"AboutMeWhereUniqueInput",
		data:"AboutMeUpsertInput"
	},
	AboutMeWhereInput:{
		AND:"AboutMeWhereInput",
		OR:"AboutMeWhereInput",
		NOT:"AboutMeWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		company:"CompanyWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		photo:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	AboutMeWhereUniqueInput:{

	},
	AboutMelinksUnionConnectInput:{
		Link:"LinkConnectInput"
	},
	AboutMelinksUnionCreateInput:{
		Link:"LinkCreateInput"
	},
	AboutMelinksUnionCreateManyInlineInput:{
		create:"AboutMelinksUnionCreateInput"
	},
	AboutMelinksUnionCreateOneInlineInput:{
		create:"AboutMelinksUnionCreateInput"
	},
	AboutMelinksUnionCreateWithPositionInput:{
		Link:"LinkCreateWithPositionInput"
	},
	AboutMelinksUnionUpdateInput:{
		Link:"LinkUpdateInput"
	},
	AboutMelinksUnionUpdateManyInlineInput:{
		create:"AboutMelinksUnionCreateWithPositionInput",
		update:"AboutMelinksUnionUpdateWithNestedWhereUniqueAndPositionInput",
		upsert:"AboutMelinksUnionUpsertWithNestedWhereUniqueAndPositionInput",
		delete:"AboutMelinksUnionWhereUniqueInput"
	},
	AboutMelinksUnionUpdateManyWithNestedWhereInput:{
		Link:"LinkUpdateManyWithNestedWhereInput"
	},
	AboutMelinksUnionUpdateOneInlineInput:{
		create:"AboutMelinksUnionCreateInput",
		update:"AboutMelinksUnionUpdateWithNestedWhereUniqueInput",
		upsert:"AboutMelinksUnionUpsertWithNestedWhereUniqueInput"
	},
	AboutMelinksUnionUpdateWithNestedWhereUniqueAndPositionInput:{
		Link:"LinkUpdateWithNestedWhereUniqueAndPositionInput"
	},
	AboutMelinksUnionUpdateWithNestedWhereUniqueInput:{
		Link:"LinkUpdateWithNestedWhereUniqueInput"
	},
	AboutMelinksUnionUpsertWithNestedWhereUniqueAndPositionInput:{
		Link:"LinkUpsertWithNestedWhereUniqueAndPositionInput"
	},
	AboutMelinksUnionUpsertWithNestedWhereUniqueInput:{
		Link:"LinkUpsertWithNestedWhereUniqueInput"
	},
	AboutMelinksUnionWhereInput:{
		Link:"LinkWhereInput"
	},
	AboutMelinksUnionWhereUniqueInput:{
		Link:"LinkWhereUniqueInput"
	},
	Asset:{
		localizations:{
			locales:"Locale"
		},
		documentInStages:{
			stages:"Stage"
		},
		publishedAt:{
			variation:"SystemDateTimeFieldVariation"
		},
		updatedAt:{
			variation:"SystemDateTimeFieldVariation"
		},
		createdAt:{
			variation:"SystemDateTimeFieldVariation"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		imageProject:{
			where:"ProjectWhereInput",
			orderBy:"ProjectOrderByInput",
			locales:"Locale"
		},
		og_imageSeo:{
			where:"SeoWhereInput",
			orderBy:"SeoOrderByInput",
			locales:"Locale"
		},
		photoAboutMe:{
			where:"AboutMeWhereInput",
			orderBy:"AboutMeOrderByInput",
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		},
		url:{
			transformation:"AssetTransformationInput"
		}
	},
	AssetConnectInput:{
		where:"AssetWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	AssetCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		imageProject:"ProjectCreateManyInlineInput",
		og_imageSeo:"SeoCreateManyInlineInput",
		iconLink:"LinkCreateManyInlineInput",
		iconSkill:"SkillCreateManyInlineInput",
		photoAboutMe:"AboutMeCreateManyInlineInput",
		localizations:"AssetCreateLocalizationsInput"
	},
	AssetCreateLocalizationDataInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime"
	},
	AssetCreateLocalizationInput:{
		data:"AssetCreateLocalizationDataInput",
		locale:"Locale"
	},
	AssetCreateLocalizationsInput:{
		create:"AssetCreateLocalizationInput"
	},
	AssetCreateManyInlineInput:{
		create:"AssetCreateInput",
		connect:"AssetWhereUniqueInput"
	},
	AssetCreateOneInlineInput:{
		create:"AssetCreateInput",
		connect:"AssetWhereUniqueInput"
	},
	AssetManyWhereInput:{
		AND:"AssetWhereInput",
		OR:"AssetWhereInput",
		NOT:"AssetWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		imageProject_every:"ProjectWhereInput",
		imageProject_some:"ProjectWhereInput",
		imageProject_none:"ProjectWhereInput",
		og_imageSeo_every:"SeoWhereInput",
		og_imageSeo_some:"SeoWhereInput",
		og_imageSeo_none:"SeoWhereInput",
		photoAboutMe_every:"AboutMeWhereInput",
		photoAboutMe_some:"AboutMeWhereInput",
		photoAboutMe_none:"AboutMeWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	AssetOrderByInput: "enum" as const,
	AssetTransformationInput:{
		image:"ImageTransformationInput",
		document:"DocumentTransformationInput"
	},
	AssetUpdateInput:{
		imageProject:"ProjectUpdateManyInlineInput",
		og_imageSeo:"SeoUpdateManyInlineInput",
		iconLink:"LinkUpdateManyInlineInput",
		iconSkill:"SkillUpdateManyInlineInput",
		photoAboutMe:"AboutMeUpdateManyInlineInput",
		localizations:"AssetUpdateLocalizationsInput"
	},
	AssetUpdateLocalizationDataInput:{

	},
	AssetUpdateLocalizationInput:{
		data:"AssetUpdateLocalizationDataInput",
		locale:"Locale"
	},
	AssetUpdateLocalizationsInput:{
		create:"AssetCreateLocalizationInput",
		update:"AssetUpdateLocalizationInput",
		upsert:"AssetUpsertLocalizationInput",
		delete:"Locale"
	},
	AssetUpdateManyInlineInput:{
		create:"AssetCreateInput",
		connect:"AssetConnectInput",
		set:"AssetWhereUniqueInput",
		update:"AssetUpdateWithNestedWhereUniqueInput",
		upsert:"AssetUpsertWithNestedWhereUniqueInput",
		disconnect:"AssetWhereUniqueInput",
		delete:"AssetWhereUniqueInput"
	},
	AssetUpdateManyInput:{
		localizations:"AssetUpdateManyLocalizationsInput"
	},
	AssetUpdateManyLocalizationDataInput:{

	},
	AssetUpdateManyLocalizationInput:{
		data:"AssetUpdateManyLocalizationDataInput",
		locale:"Locale"
	},
	AssetUpdateManyLocalizationsInput:{
		update:"AssetUpdateManyLocalizationInput"
	},
	AssetUpdateManyWithNestedWhereInput:{
		where:"AssetWhereInput",
		data:"AssetUpdateManyInput"
	},
	AssetUpdateOneInlineInput:{
		create:"AssetCreateInput",
		update:"AssetUpdateWithNestedWhereUniqueInput",
		upsert:"AssetUpsertWithNestedWhereUniqueInput",
		connect:"AssetWhereUniqueInput"
	},
	AssetUpdateWithNestedWhereUniqueInput:{
		where:"AssetWhereUniqueInput",
		data:"AssetUpdateInput"
	},
	AssetUpsertInput:{
		create:"AssetCreateInput",
		update:"AssetUpdateInput"
	},
	AssetUpsertLocalizationInput:{
		update:"AssetUpdateLocalizationDataInput",
		create:"AssetCreateLocalizationDataInput",
		locale:"Locale"
	},
	AssetUpsertWithNestedWhereUniqueInput:{
		where:"AssetWhereUniqueInput",
		data:"AssetUpsertInput"
	},
	AssetWhereInput:{
		AND:"AssetWhereInput",
		OR:"AssetWhereInput",
		NOT:"AssetWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		imageProject_every:"ProjectWhereInput",
		imageProject_some:"ProjectWhereInput",
		imageProject_none:"ProjectWhereInput",
		og_imageSeo_every:"SeoWhereInput",
		og_imageSeo_some:"SeoWhereInput",
		og_imageSeo_none:"SeoWhereInput",
		photoAboutMe_every:"AboutMeWhereInput",
		photoAboutMe_some:"AboutMeWhereInput",
		photoAboutMe_none:"AboutMeWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	AssetWhereUniqueInput:{

	},
	ColorInput:{
		hex:"Hex",
		rgba:"RGBAInput"
	},
	CompanyConnectInput:{
		where:"CompanyWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	CompanyCreateInput:{

	},
	CompanyCreateManyInlineInput:{
		create:"CompanyCreateInput"
	},
	CompanyCreateOneInlineInput:{
		create:"CompanyCreateInput"
	},
	CompanyCreateWithPositionInput:{
		position:"ConnectPositionInput",
		data:"CompanyCreateInput"
	},
	CompanyManyWhereInput:{
		AND:"CompanyWhereInput",
		OR:"CompanyWhereInput",
		NOT:"CompanyWhereInput"
	},
	CompanyOrderByInput: "enum" as const,
	CompanyParentConnectInput:{
		AboutMe:"AboutMeConnectInput"
	},
	CompanyParentCreateInput:{
		AboutMe:"AboutMeCreateInput"
	},
	CompanyParentCreateManyInlineInput:{
		create:"CompanyParentCreateInput",
		connect:"CompanyParentWhereUniqueInput"
	},
	CompanyParentCreateOneInlineInput:{
		create:"CompanyParentCreateInput",
		connect:"CompanyParentWhereUniqueInput"
	},
	CompanyParentUpdateInput:{
		AboutMe:"AboutMeUpdateInput"
	},
	CompanyParentUpdateManyInlineInput:{
		create:"CompanyParentCreateInput",
		connect:"CompanyParentConnectInput",
		set:"CompanyParentWhereUniqueInput",
		update:"CompanyParentUpdateWithNestedWhereUniqueInput",
		upsert:"CompanyParentUpsertWithNestedWhereUniqueInput",
		disconnect:"CompanyParentWhereUniqueInput",
		delete:"CompanyParentWhereUniqueInput"
	},
	CompanyParentUpdateManyWithNestedWhereInput:{
		AboutMe:"AboutMeUpdateManyWithNestedWhereInput"
	},
	CompanyParentUpdateOneInlineInput:{
		create:"CompanyParentCreateInput",
		update:"CompanyParentUpdateWithNestedWhereUniqueInput",
		upsert:"CompanyParentUpsertWithNestedWhereUniqueInput",
		connect:"CompanyParentWhereUniqueInput"
	},
	CompanyParentUpdateWithNestedWhereUniqueInput:{
		AboutMe:"AboutMeUpdateWithNestedWhereUniqueInput"
	},
	CompanyParentUpsertWithNestedWhereUniqueInput:{
		AboutMe:"AboutMeUpsertWithNestedWhereUniqueInput"
	},
	CompanyParentWhereInput:{
		AboutMe:"AboutMeWhereInput"
	},
	CompanyParentWhereUniqueInput:{
		AboutMe:"AboutMeWhereUniqueInput"
	},
	CompanyUpdateInput:{

	},
	CompanyUpdateManyInlineInput:{
		create:"CompanyCreateWithPositionInput",
		update:"CompanyUpdateWithNestedWhereUniqueAndPositionInput",
		upsert:"CompanyUpsertWithNestedWhereUniqueAndPositionInput",
		delete:"CompanyWhereUniqueInput"
	},
	CompanyUpdateManyInput:{

	},
	CompanyUpdateManyWithNestedWhereInput:{
		where:"CompanyWhereInput",
		data:"CompanyUpdateManyInput"
	},
	CompanyUpdateOneInlineInput:{
		create:"CompanyCreateInput",
		update:"CompanyUpdateWithNestedWhereUniqueInput",
		upsert:"CompanyUpsertWithNestedWhereUniqueInput"
	},
	CompanyUpdateWithNestedWhereUniqueAndPositionInput:{
		where:"CompanyWhereUniqueInput",
		position:"ConnectPositionInput",
		data:"CompanyUpdateInput"
	},
	CompanyUpdateWithNestedWhereUniqueInput:{
		where:"CompanyWhereUniqueInput",
		data:"CompanyUpdateInput"
	},
	CompanyUpsertInput:{
		create:"CompanyCreateInput",
		update:"CompanyUpdateInput"
	},
	CompanyUpsertWithNestedWhereUniqueAndPositionInput:{
		where:"CompanyWhereUniqueInput",
		position:"ConnectPositionInput",
		data:"CompanyUpsertInput"
	},
	CompanyUpsertWithNestedWhereUniqueInput:{
		where:"CompanyWhereUniqueInput",
		data:"CompanyUpsertInput"
	},
	CompanyWhereInput:{
		AND:"CompanyWhereInput",
		OR:"CompanyWhereInput",
		NOT:"CompanyWhereInput"
	},
	CompanyWhereUniqueInput:{

	},
	ConnectPositionInput:{

	},
	Date: `scalar.Date` as const,
	DateTime: `scalar.DateTime` as const,
	DocumentFileTypes: "enum" as const,
	DocumentOutputInput:{
		format:"DocumentFileTypes"
	},
	DocumentTransformationInput:{
		output:"DocumentOutputInput"
	},
	Hex: `scalar.Hex` as const,
	ImageFit: "enum" as const,
	ImageResizeInput:{
		fit:"ImageFit"
	},
	ImageTransformationInput:{
		resize:"ImageResizeInput"
	},
	Json: `scalar.Json` as const,
	Link:{
		icon:{
			locales:"Locale"
		}
	},
	LinkConnectInput:{
		where:"LinkWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	LinkCreateInput:{
		icon:"AssetCreateOneInlineInput"
	},
	LinkCreateManyInlineInput:{
		create:"LinkCreateInput"
	},
	LinkCreateOneInlineInput:{
		create:"LinkCreateInput"
	},
	LinkCreateWithPositionInput:{
		position:"ConnectPositionInput",
		data:"LinkCreateInput"
	},
	LinkManyWhereInput:{
		AND:"LinkWhereInput",
		OR:"LinkWhereInput",
		NOT:"LinkWhereInput",
		icon:"AssetWhereInput"
	},
	LinkOrderByInput: "enum" as const,
	LinkParentConnectInput:{
		AboutMe:"AboutMeConnectInput"
	},
	LinkParentCreateInput:{
		AboutMe:"AboutMeCreateInput"
	},
	LinkParentCreateManyInlineInput:{
		create:"LinkParentCreateInput",
		connect:"LinkParentWhereUniqueInput"
	},
	LinkParentCreateOneInlineInput:{
		create:"LinkParentCreateInput",
		connect:"LinkParentWhereUniqueInput"
	},
	LinkParentUpdateInput:{
		AboutMe:"AboutMeUpdateInput"
	},
	LinkParentUpdateManyInlineInput:{
		create:"LinkParentCreateInput",
		connect:"LinkParentConnectInput",
		set:"LinkParentWhereUniqueInput",
		update:"LinkParentUpdateWithNestedWhereUniqueInput",
		upsert:"LinkParentUpsertWithNestedWhereUniqueInput",
		disconnect:"LinkParentWhereUniqueInput",
		delete:"LinkParentWhereUniqueInput"
	},
	LinkParentUpdateManyWithNestedWhereInput:{
		AboutMe:"AboutMeUpdateManyWithNestedWhereInput"
	},
	LinkParentUpdateOneInlineInput:{
		create:"LinkParentCreateInput",
		update:"LinkParentUpdateWithNestedWhereUniqueInput",
		upsert:"LinkParentUpsertWithNestedWhereUniqueInput",
		connect:"LinkParentWhereUniqueInput"
	},
	LinkParentUpdateWithNestedWhereUniqueInput:{
		AboutMe:"AboutMeUpdateWithNestedWhereUniqueInput"
	},
	LinkParentUpsertWithNestedWhereUniqueInput:{
		AboutMe:"AboutMeUpsertWithNestedWhereUniqueInput"
	},
	LinkParentWhereInput:{
		AboutMe:"AboutMeWhereInput"
	},
	LinkParentWhereUniqueInput:{
		AboutMe:"AboutMeWhereUniqueInput"
	},
	LinkUpdateInput:{
		icon:"AssetUpdateOneInlineInput"
	},
	LinkUpdateManyInlineInput:{
		create:"LinkCreateWithPositionInput",
		update:"LinkUpdateWithNestedWhereUniqueAndPositionInput",
		upsert:"LinkUpsertWithNestedWhereUniqueAndPositionInput",
		delete:"LinkWhereUniqueInput"
	},
	LinkUpdateManyInput:{

	},
	LinkUpdateManyWithNestedWhereInput:{
		where:"LinkWhereInput",
		data:"LinkUpdateManyInput"
	},
	LinkUpdateOneInlineInput:{
		create:"LinkCreateInput",
		update:"LinkUpdateWithNestedWhereUniqueInput",
		upsert:"LinkUpsertWithNestedWhereUniqueInput"
	},
	LinkUpdateWithNestedWhereUniqueAndPositionInput:{
		where:"LinkWhereUniqueInput",
		position:"ConnectPositionInput",
		data:"LinkUpdateInput"
	},
	LinkUpdateWithNestedWhereUniqueInput:{
		where:"LinkWhereUniqueInput",
		data:"LinkUpdateInput"
	},
	LinkUpsertInput:{
		create:"LinkCreateInput",
		update:"LinkUpdateInput"
	},
	LinkUpsertWithNestedWhereUniqueAndPositionInput:{
		where:"LinkWhereUniqueInput",
		position:"ConnectPositionInput",
		data:"LinkUpsertInput"
	},
	LinkUpsertWithNestedWhereUniqueInput:{
		where:"LinkWhereUniqueInput",
		data:"LinkUpsertInput"
	},
	LinkWhereInput:{
		AND:"LinkWhereInput",
		OR:"LinkWhereInput",
		NOT:"LinkWhereInput",
		icon:"AssetWhereInput"
	},
	LinkWhereUniqueInput:{

	},
	Locale: "enum" as const,
	Location:{
		distance:{
			from:"LocationInput"
		}
	},
	LocationInput:{

	},
	Long: `scalar.Long` as const,
	Mutation:{
		createAsset:{
			data:"AssetCreateInput"
		},
		updateAsset:{
			where:"AssetWhereUniqueInput",
			data:"AssetUpdateInput"
		},
		deleteAsset:{
			where:"AssetWhereUniqueInput"
		},
		upsertAsset:{
			where:"AssetWhereUniqueInput",
			upsert:"AssetUpsertInput"
		},
		publishAsset:{
			where:"AssetWhereUniqueInput",
			locales:"Locale",
			to:"Stage"
		},
		unpublishAsset:{
			where:"AssetWhereUniqueInput",
			from:"Stage",
			locales:"Locale"
		},
		updateManyAssetsConnection:{
			where:"AssetManyWhereInput",
			data:"AssetUpdateManyInput"
		},
		deleteManyAssetsConnection:{
			where:"AssetManyWhereInput"
		},
		publishManyAssetsConnection:{
			where:"AssetManyWhereInput",
			from:"Stage",
			to:"Stage",
			locales:"Locale"
		},
		unpublishManyAssetsConnection:{
			where:"AssetManyWhereInput",
			stage:"Stage",
			from:"Stage",
			locales:"Locale"
		},
		updateManyAssets:{
			where:"AssetManyWhereInput",
			data:"AssetUpdateManyInput"
		},
		deleteManyAssets:{
			where:"AssetManyWhereInput"
		},
		publishManyAssets:{
			where:"AssetManyWhereInput",
			to:"Stage",
			locales:"Locale"
		},
		unpublishManyAssets:{
			where:"AssetManyWhereInput",
			from:"Stage",
			locales:"Locale"
		},
		schedulePublishAsset:{
			where:"AssetWhereUniqueInput",
			locales:"Locale",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishAsset:{
			where:"AssetWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime",
			locales:"Locale"
		},
		deleteScheduledOperation:{
			where:"ScheduledOperationWhereUniqueInput"
		},
		createScheduledRelease:{
			data:"ScheduledReleaseCreateInput"
		},
		updateScheduledRelease:{
			where:"ScheduledReleaseWhereUniqueInput",
			data:"ScheduledReleaseUpdateInput"
		},
		deleteScheduledRelease:{
			where:"ScheduledReleaseWhereUniqueInput"
		},
		createProject:{
			data:"ProjectCreateInput"
		},
		updateProject:{
			where:"ProjectWhereUniqueInput",
			data:"ProjectUpdateInput"
		},
		deleteProject:{
			where:"ProjectWhereUniqueInput"
		},
		upsertProject:{
			where:"ProjectWhereUniqueInput",
			upsert:"ProjectUpsertInput"
		},
		publishProject:{
			where:"ProjectWhereUniqueInput",
			to:"Stage"
		},
		unpublishProject:{
			where:"ProjectWhereUniqueInput",
			from:"Stage"
		},
		updateManyProjectsConnection:{
			where:"ProjectManyWhereInput",
			data:"ProjectUpdateManyInput"
		},
		deleteManyProjectsConnection:{
			where:"ProjectManyWhereInput"
		},
		publishManyProjectsConnection:{
			where:"ProjectManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManyProjectsConnection:{
			where:"ProjectManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManyProjects:{
			where:"ProjectManyWhereInput",
			data:"ProjectUpdateManyInput"
		},
		deleteManyProjects:{
			where:"ProjectManyWhereInput"
		},
		publishManyProjects:{
			where:"ProjectManyWhereInput",
			to:"Stage"
		},
		unpublishManyProjects:{
			where:"ProjectManyWhereInput",
			from:"Stage"
		},
		schedulePublishProject:{
			where:"ProjectWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishProject:{
			where:"ProjectWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		},
		createSeo:{
			data:"SeoCreateInput"
		},
		updateSeo:{
			where:"SeoWhereUniqueInput",
			data:"SeoUpdateInput"
		},
		deleteSeo:{
			where:"SeoWhereUniqueInput"
		},
		upsertSeo:{
			where:"SeoWhereUniqueInput",
			upsert:"SeoUpsertInput"
		},
		publishSeo:{
			where:"SeoWhereUniqueInput",
			to:"Stage"
		},
		unpublishSeo:{
			where:"SeoWhereUniqueInput",
			from:"Stage"
		},
		updateManySeosConnection:{
			where:"SeoManyWhereInput",
			data:"SeoUpdateManyInput"
		},
		deleteManySeosConnection:{
			where:"SeoManyWhereInput"
		},
		publishManySeosConnection:{
			where:"SeoManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManySeosConnection:{
			where:"SeoManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManySeos:{
			where:"SeoManyWhereInput",
			data:"SeoUpdateManyInput"
		},
		deleteManySeos:{
			where:"SeoManyWhereInput"
		},
		publishManySeos:{
			where:"SeoManyWhereInput",
			to:"Stage"
		},
		unpublishManySeos:{
			where:"SeoManyWhereInput",
			from:"Stage"
		},
		schedulePublishSeo:{
			where:"SeoWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishSeo:{
			where:"SeoWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		},
		createAboutMe:{
			data:"AboutMeCreateInput"
		},
		updateAboutMe:{
			where:"AboutMeWhereUniqueInput",
			data:"AboutMeUpdateInput"
		},
		deleteAboutMe:{
			where:"AboutMeWhereUniqueInput"
		},
		upsertAboutMe:{
			where:"AboutMeWhereUniqueInput",
			upsert:"AboutMeUpsertInput"
		},
		publishAboutMe:{
			where:"AboutMeWhereUniqueInput",
			to:"Stage"
		},
		unpublishAboutMe:{
			where:"AboutMeWhereUniqueInput",
			from:"Stage"
		},
		updateManyAboutMesConnection:{
			where:"AboutMeManyWhereInput",
			data:"AboutMeUpdateManyInput"
		},
		deleteManyAboutMesConnection:{
			where:"AboutMeManyWhereInput"
		},
		publishManyAboutMesConnection:{
			where:"AboutMeManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManyAboutMesConnection:{
			where:"AboutMeManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManyAboutMes:{
			where:"AboutMeManyWhereInput",
			data:"AboutMeUpdateManyInput"
		},
		deleteManyAboutMes:{
			where:"AboutMeManyWhereInput"
		},
		publishManyAboutMes:{
			where:"AboutMeManyWhereInput",
			to:"Stage"
		},
		unpublishManyAboutMes:{
			where:"AboutMeManyWhereInput",
			from:"Stage"
		},
		schedulePublishAboutMe:{
			where:"AboutMeWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishAboutMe:{
			where:"AboutMeWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		},
		createSkillCategory:{
			data:"SkillCategoryCreateInput"
		},
		updateSkillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			data:"SkillCategoryUpdateInput"
		},
		deleteSkillCategory:{
			where:"SkillCategoryWhereUniqueInput"
		},
		upsertSkillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			upsert:"SkillCategoryUpsertInput"
		},
		publishSkillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			to:"Stage"
		},
		unpublishSkillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			from:"Stage"
		},
		updateManySkillCategoriesConnection:{
			where:"SkillCategoryManyWhereInput",
			data:"SkillCategoryUpdateManyInput"
		},
		deleteManySkillCategoriesConnection:{
			where:"SkillCategoryManyWhereInput"
		},
		publishManySkillCategoriesConnection:{
			where:"SkillCategoryManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManySkillCategoriesConnection:{
			where:"SkillCategoryManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManySkillCategories:{
			where:"SkillCategoryManyWhereInput",
			data:"SkillCategoryUpdateManyInput"
		},
		deleteManySkillCategories:{
			where:"SkillCategoryManyWhereInput"
		},
		publishManySkillCategories:{
			where:"SkillCategoryManyWhereInput",
			to:"Stage"
		},
		unpublishManySkillCategories:{
			where:"SkillCategoryManyWhereInput",
			from:"Stage"
		},
		schedulePublishSkillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishSkillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		}
	},
	Project:{
		documentInStages:{
			stages:"Stage"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		image:{
			where:"AssetWhereInput",
			orderBy:"AssetOrderByInput",
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	ProjectConnectInput:{
		where:"ProjectWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	ProjectCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		image:"AssetCreateManyInlineInput",
		stack:"Technologies"
	},
	ProjectCreateManyInlineInput:{
		create:"ProjectCreateInput",
		connect:"ProjectWhereUniqueInput"
	},
	ProjectCreateOneInlineInput:{
		create:"ProjectCreateInput",
		connect:"ProjectWhereUniqueInput"
	},
	ProjectManyWhereInput:{
		AND:"ProjectWhereInput",
		OR:"ProjectWhereInput",
		NOT:"ProjectWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image_every:"AssetWhereInput",
		image_some:"AssetWhereInput",
		image_none:"AssetWhereInput",
		stack:"Technologies",
		stack_not:"Technologies",
		stack_contains_all:"Technologies",
		stack_contains_some:"Technologies",
		stack_contains_none:"Technologies",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	ProjectOrderByInput: "enum" as const,
	ProjectUpdateInput:{
		image:"AssetUpdateManyInlineInput",
		stack:"Technologies"
	},
	ProjectUpdateManyInlineInput:{
		create:"ProjectCreateInput",
		connect:"ProjectConnectInput",
		set:"ProjectWhereUniqueInput",
		update:"ProjectUpdateWithNestedWhereUniqueInput",
		upsert:"ProjectUpsertWithNestedWhereUniqueInput",
		disconnect:"ProjectWhereUniqueInput",
		delete:"ProjectWhereUniqueInput"
	},
	ProjectUpdateManyInput:{
		stack:"Technologies"
	},
	ProjectUpdateManyWithNestedWhereInput:{
		where:"ProjectWhereInput",
		data:"ProjectUpdateManyInput"
	},
	ProjectUpdateOneInlineInput:{
		create:"ProjectCreateInput",
		update:"ProjectUpdateWithNestedWhereUniqueInput",
		upsert:"ProjectUpsertWithNestedWhereUniqueInput",
		connect:"ProjectWhereUniqueInput"
	},
	ProjectUpdateWithNestedWhereUniqueInput:{
		where:"ProjectWhereUniqueInput",
		data:"ProjectUpdateInput"
	},
	ProjectUpsertInput:{
		create:"ProjectCreateInput",
		update:"ProjectUpdateInput"
	},
	ProjectUpsertWithNestedWhereUniqueInput:{
		where:"ProjectWhereUniqueInput",
		data:"ProjectUpsertInput"
	},
	ProjectWhereInput:{
		AND:"ProjectWhereInput",
		OR:"ProjectWhereInput",
		NOT:"ProjectWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image_every:"AssetWhereInput",
		image_some:"AssetWhereInput",
		image_none:"AssetWhereInput",
		stack:"Technologies",
		stack_not:"Technologies",
		stack_contains_all:"Technologies",
		stack_contains_some:"Technologies",
		stack_contains_none:"Technologies",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	ProjectWhereUniqueInput:{

	},
	PublishLocaleInput:{
		locale:"Locale",
		stages:"Stage"
	},
	Query:{
		node:{
			stage:"Stage",
			locales:"Locale"
		},
		users:{
			where:"UserWhereInput",
			orderBy:"UserOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		user:{
			where:"UserWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		usersConnection:{
			where:"UserWhereInput",
			orderBy:"UserOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		assets:{
			where:"AssetWhereInput",
			orderBy:"AssetOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		asset:{
			where:"AssetWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		assetsConnection:{
			where:"AssetWhereInput",
			orderBy:"AssetOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		assetVersion:{
			where:"VersionWhereInput"
		},
		scheduledOperations:{
			where:"ScheduledOperationWhereInput",
			orderBy:"ScheduledOperationOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledOperation:{
			where:"ScheduledOperationWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledOperationsConnection:{
			where:"ScheduledOperationWhereInput",
			orderBy:"ScheduledOperationOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledReleases:{
			where:"ScheduledReleaseWhereInput",
			orderBy:"ScheduledReleaseOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledRelease:{
			where:"ScheduledReleaseWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledReleasesConnection:{
			where:"ScheduledReleaseWhereInput",
			orderBy:"ScheduledReleaseOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		projects:{
			where:"ProjectWhereInput",
			orderBy:"ProjectOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		project:{
			where:"ProjectWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		projectsConnection:{
			where:"ProjectWhereInput",
			orderBy:"ProjectOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		projectVersion:{
			where:"VersionWhereInput"
		},
		seos:{
			where:"SeoWhereInput",
			orderBy:"SeoOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		seo:{
			where:"SeoWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		seosConnection:{
			where:"SeoWhereInput",
			orderBy:"SeoOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		seoVersion:{
			where:"VersionWhereInput"
		},
		aboutMes:{
			where:"AboutMeWhereInput",
			orderBy:"AboutMeOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		aboutMe:{
			where:"AboutMeWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		aboutMesConnection:{
			where:"AboutMeWhereInput",
			orderBy:"AboutMeOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		aboutMeVersion:{
			where:"VersionWhereInput"
		},
		skillCategories:{
			where:"SkillCategoryWhereInput",
			orderBy:"SkillCategoryOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		skillCategory:{
			where:"SkillCategoryWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		skillCategoriesConnection:{
			where:"SkillCategoryWhereInput",
			orderBy:"SkillCategoryOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		skillCategoryVersion:{
			where:"VersionWhereInput"
		}
	},
	RGBAHue: `scalar.RGBAHue` as const,
	RGBAInput:{
		r:"RGBAHue",
		g:"RGBAHue",
		b:"RGBAHue",
		a:"RGBATransparency"
	},
	RGBATransparency: `scalar.RGBATransparency` as const,
	RichTextAST: `scalar.RichTextAST` as const,
	ScheduledOperation:{
		documentInStages:{
			stages:"Stage"
		},
		release:{
			locales:"Locale"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		affectedDocuments:{
			locales:"Locale"
		}
	},
	ScheduledOperationConnectInput:{
		where:"ScheduledOperationWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	ScheduledOperationCreateManyInlineInput:{
		connect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationCreateOneInlineInput:{
		connect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationManyWhereInput:{
		AND:"ScheduledOperationWhereInput",
		OR:"ScheduledOperationWhereInput",
		NOT:"ScheduledOperationWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		release:"ScheduledReleaseWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledOperationStatus",
		status_not:"ScheduledOperationStatus",
		status_in:"ScheduledOperationStatus",
		status_not_in:"ScheduledOperationStatus"
	},
	ScheduledOperationOrderByInput: "enum" as const,
	ScheduledOperationStatus: "enum" as const,
	ScheduledOperationUpdateManyInlineInput:{
		connect:"ScheduledOperationConnectInput",
		set:"ScheduledOperationWhereUniqueInput",
		disconnect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationUpdateOneInlineInput:{
		connect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationWhereInput:{
		AND:"ScheduledOperationWhereInput",
		OR:"ScheduledOperationWhereInput",
		NOT:"ScheduledOperationWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		release:"ScheduledReleaseWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledOperationStatus",
		status_not:"ScheduledOperationStatus",
		status_in:"ScheduledOperationStatus",
		status_not_in:"ScheduledOperationStatus"
	},
	ScheduledOperationWhereUniqueInput:{

	},
	ScheduledRelease:{
		documentInStages:{
			stages:"Stage"
		},
		operations:{
			where:"ScheduledOperationWhereInput",
			orderBy:"ScheduledOperationOrderByInput",
			locales:"Locale"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		}
	},
	ScheduledReleaseConnectInput:{
		where:"ScheduledReleaseWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	ScheduledReleaseCreateInput:{
		releaseAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime"
	},
	ScheduledReleaseCreateManyInlineInput:{
		create:"ScheduledReleaseCreateInput",
		connect:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseCreateOneInlineInput:{
		create:"ScheduledReleaseCreateInput",
		connect:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseManyWhereInput:{
		AND:"ScheduledReleaseWhereInput",
		OR:"ScheduledReleaseWhereInput",
		NOT:"ScheduledReleaseWhereInput",
		releaseAt:"DateTime",
		releaseAt_not:"DateTime",
		releaseAt_in:"DateTime",
		releaseAt_not_in:"DateTime",
		releaseAt_lt:"DateTime",
		releaseAt_lte:"DateTime",
		releaseAt_gt:"DateTime",
		releaseAt_gte:"DateTime",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		operations_every:"ScheduledOperationWhereInput",
		operations_some:"ScheduledOperationWhereInput",
		operations_none:"ScheduledOperationWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledReleaseStatus",
		status_not:"ScheduledReleaseStatus",
		status_in:"ScheduledReleaseStatus",
		status_not_in:"ScheduledReleaseStatus"
	},
	ScheduledReleaseOrderByInput: "enum" as const,
	ScheduledReleaseStatus: "enum" as const,
	ScheduledReleaseUpdateInput:{
		releaseAt:"DateTime"
	},
	ScheduledReleaseUpdateManyInlineInput:{
		create:"ScheduledReleaseCreateInput",
		connect:"ScheduledReleaseConnectInput",
		set:"ScheduledReleaseWhereUniqueInput",
		update:"ScheduledReleaseUpdateWithNestedWhereUniqueInput",
		upsert:"ScheduledReleaseUpsertWithNestedWhereUniqueInput",
		disconnect:"ScheduledReleaseWhereUniqueInput",
		delete:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseUpdateManyInput:{
		releaseAt:"DateTime"
	},
	ScheduledReleaseUpdateManyWithNestedWhereInput:{
		where:"ScheduledReleaseWhereInput",
		data:"ScheduledReleaseUpdateManyInput"
	},
	ScheduledReleaseUpdateOneInlineInput:{
		create:"ScheduledReleaseCreateInput",
		update:"ScheduledReleaseUpdateWithNestedWhereUniqueInput",
		upsert:"ScheduledReleaseUpsertWithNestedWhereUniqueInput",
		connect:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseUpdateWithNestedWhereUniqueInput:{
		where:"ScheduledReleaseWhereUniqueInput",
		data:"ScheduledReleaseUpdateInput"
	},
	ScheduledReleaseUpsertInput:{
		create:"ScheduledReleaseCreateInput",
		update:"ScheduledReleaseUpdateInput"
	},
	ScheduledReleaseUpsertWithNestedWhereUniqueInput:{
		where:"ScheduledReleaseWhereUniqueInput",
		data:"ScheduledReleaseUpsertInput"
	},
	ScheduledReleaseWhereInput:{
		AND:"ScheduledReleaseWhereInput",
		OR:"ScheduledReleaseWhereInput",
		NOT:"ScheduledReleaseWhereInput",
		releaseAt:"DateTime",
		releaseAt_not:"DateTime",
		releaseAt_in:"DateTime",
		releaseAt_not_in:"DateTime",
		releaseAt_lt:"DateTime",
		releaseAt_lte:"DateTime",
		releaseAt_gt:"DateTime",
		releaseAt_gte:"DateTime",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		operations_every:"ScheduledOperationWhereInput",
		operations_some:"ScheduledOperationWhereInput",
		operations_none:"ScheduledOperationWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledReleaseStatus",
		status_not:"ScheduledReleaseStatus",
		status_in:"ScheduledReleaseStatus",
		status_not_in:"ScheduledReleaseStatus"
	},
	ScheduledReleaseWhereUniqueInput:{

	},
	Seo:{
		documentInStages:{
			stages:"Stage"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		og_image:{
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	SeoConnectInput:{
		where:"SeoWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	SeoCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		og_image:"AssetCreateOneInlineInput"
	},
	SeoCreateManyInlineInput:{
		create:"SeoCreateInput",
		connect:"SeoWhereUniqueInput"
	},
	SeoCreateOneInlineInput:{
		create:"SeoCreateInput",
		connect:"SeoWhereUniqueInput"
	},
	SeoManyWhereInput:{
		AND:"SeoWhereInput",
		OR:"SeoWhereInput",
		NOT:"SeoWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		og_image:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SeoOrderByInput: "enum" as const,
	SeoUpdateInput:{
		og_image:"AssetUpdateOneInlineInput"
	},
	SeoUpdateManyInlineInput:{
		create:"SeoCreateInput",
		connect:"SeoConnectInput",
		set:"SeoWhereUniqueInput",
		update:"SeoUpdateWithNestedWhereUniqueInput",
		upsert:"SeoUpsertWithNestedWhereUniqueInput",
		disconnect:"SeoWhereUniqueInput",
		delete:"SeoWhereUniqueInput"
	},
	SeoUpdateManyInput:{

	},
	SeoUpdateManyWithNestedWhereInput:{
		where:"SeoWhereInput",
		data:"SeoUpdateManyInput"
	},
	SeoUpdateOneInlineInput:{
		create:"SeoCreateInput",
		update:"SeoUpdateWithNestedWhereUniqueInput",
		upsert:"SeoUpsertWithNestedWhereUniqueInput",
		connect:"SeoWhereUniqueInput"
	},
	SeoUpdateWithNestedWhereUniqueInput:{
		where:"SeoWhereUniqueInput",
		data:"SeoUpdateInput"
	},
	SeoUpsertInput:{
		create:"SeoCreateInput",
		update:"SeoUpdateInput"
	},
	SeoUpsertWithNestedWhereUniqueInput:{
		where:"SeoWhereUniqueInput",
		data:"SeoUpsertInput"
	},
	SeoWhereInput:{
		AND:"SeoWhereInput",
		OR:"SeoWhereInput",
		NOT:"SeoWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		og_image:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SeoWhereUniqueInput:{

	},
	Skill:{
		icon:{
			locales:"Locale"
		}
	},
	SkillCategory:{
		documentInStages:{
			stages:"Stage"
		},
		skillsList:{
			locales:"Locale"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	SkillCategoryConnectInput:{
		where:"SkillCategoryWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	SkillCategoryCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		skillsList:"SkillCategoryskillsListUnionCreateManyInlineInput"
	},
	SkillCategoryCreateManyInlineInput:{
		create:"SkillCategoryCreateInput",
		connect:"SkillCategoryWhereUniqueInput"
	},
	SkillCategoryCreateOneInlineInput:{
		create:"SkillCategoryCreateInput",
		connect:"SkillCategoryWhereUniqueInput"
	},
	SkillCategoryManyWhereInput:{
		AND:"SkillCategoryWhereInput",
		OR:"SkillCategoryWhereInput",
		NOT:"SkillCategoryWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SkillCategoryOrderByInput: "enum" as const,
	SkillCategoryUpdateInput:{
		skillsList:"SkillCategoryskillsListUnionUpdateManyInlineInput"
	},
	SkillCategoryUpdateManyInlineInput:{
		create:"SkillCategoryCreateInput",
		connect:"SkillCategoryConnectInput",
		set:"SkillCategoryWhereUniqueInput",
		update:"SkillCategoryUpdateWithNestedWhereUniqueInput",
		upsert:"SkillCategoryUpsertWithNestedWhereUniqueInput",
		disconnect:"SkillCategoryWhereUniqueInput",
		delete:"SkillCategoryWhereUniqueInput"
	},
	SkillCategoryUpdateManyInput:{

	},
	SkillCategoryUpdateManyWithNestedWhereInput:{
		where:"SkillCategoryWhereInput",
		data:"SkillCategoryUpdateManyInput"
	},
	SkillCategoryUpdateOneInlineInput:{
		create:"SkillCategoryCreateInput",
		update:"SkillCategoryUpdateWithNestedWhereUniqueInput",
		upsert:"SkillCategoryUpsertWithNestedWhereUniqueInput",
		connect:"SkillCategoryWhereUniqueInput"
	},
	SkillCategoryUpdateWithNestedWhereUniqueInput:{
		where:"SkillCategoryWhereUniqueInput",
		data:"SkillCategoryUpdateInput"
	},
	SkillCategoryUpsertInput:{
		create:"SkillCategoryCreateInput",
		update:"SkillCategoryUpdateInput"
	},
	SkillCategoryUpsertWithNestedWhereUniqueInput:{
		where:"SkillCategoryWhereUniqueInput",
		data:"SkillCategoryUpsertInput"
	},
	SkillCategoryWhereInput:{
		AND:"SkillCategoryWhereInput",
		OR:"SkillCategoryWhereInput",
		NOT:"SkillCategoryWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SkillCategoryWhereUniqueInput:{

	},
	SkillCategoryskillsListUnionConnectInput:{
		Skill:"SkillConnectInput"
	},
	SkillCategoryskillsListUnionCreateInput:{
		Skill:"SkillCreateInput"
	},
	SkillCategoryskillsListUnionCreateManyInlineInput:{
		create:"SkillCategoryskillsListUnionCreateInput"
	},
	SkillCategoryskillsListUnionCreateOneInlineInput:{
		create:"SkillCategoryskillsListUnionCreateInput"
	},
	SkillCategoryskillsListUnionCreateWithPositionInput:{
		Skill:"SkillCreateWithPositionInput"
	},
	SkillCategoryskillsListUnionUpdateInput:{
		Skill:"SkillUpdateInput"
	},
	SkillCategoryskillsListUnionUpdateManyInlineInput:{
		create:"SkillCategoryskillsListUnionCreateWithPositionInput",
		update:"SkillCategoryskillsListUnionUpdateWithNestedWhereUniqueAndPositionInput",
		upsert:"SkillCategoryskillsListUnionUpsertWithNestedWhereUniqueAndPositionInput",
		delete:"SkillCategoryskillsListUnionWhereUniqueInput"
	},
	SkillCategoryskillsListUnionUpdateManyWithNestedWhereInput:{
		Skill:"SkillUpdateManyWithNestedWhereInput"
	},
	SkillCategoryskillsListUnionUpdateOneInlineInput:{
		create:"SkillCategoryskillsListUnionCreateInput",
		update:"SkillCategoryskillsListUnionUpdateWithNestedWhereUniqueInput",
		upsert:"SkillCategoryskillsListUnionUpsertWithNestedWhereUniqueInput"
	},
	SkillCategoryskillsListUnionUpdateWithNestedWhereUniqueAndPositionInput:{
		Skill:"SkillUpdateWithNestedWhereUniqueAndPositionInput"
	},
	SkillCategoryskillsListUnionUpdateWithNestedWhereUniqueInput:{
		Skill:"SkillUpdateWithNestedWhereUniqueInput"
	},
	SkillCategoryskillsListUnionUpsertWithNestedWhereUniqueAndPositionInput:{
		Skill:"SkillUpsertWithNestedWhereUniqueAndPositionInput"
	},
	SkillCategoryskillsListUnionUpsertWithNestedWhereUniqueInput:{
		Skill:"SkillUpsertWithNestedWhereUniqueInput"
	},
	SkillCategoryskillsListUnionWhereInput:{
		Skill:"SkillWhereInput"
	},
	SkillCategoryskillsListUnionWhereUniqueInput:{
		Skill:"SkillWhereUniqueInput"
	},
	SkillConnectInput:{
		where:"SkillWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	SkillCreateInput:{
		icon:"AssetCreateOneInlineInput"
	},
	SkillCreateManyInlineInput:{
		create:"SkillCreateInput"
	},
	SkillCreateOneInlineInput:{
		create:"SkillCreateInput"
	},
	SkillCreateWithPositionInput:{
		position:"ConnectPositionInput",
		data:"SkillCreateInput"
	},
	SkillManyWhereInput:{
		AND:"SkillWhereInput",
		OR:"SkillWhereInput",
		NOT:"SkillWhereInput",
		icon:"AssetWhereInput"
	},
	SkillOrderByInput: "enum" as const,
	SkillParentConnectInput:{
		SkillCategory:"SkillCategoryConnectInput"
	},
	SkillParentCreateInput:{
		SkillCategory:"SkillCategoryCreateInput"
	},
	SkillParentCreateManyInlineInput:{
		create:"SkillParentCreateInput",
		connect:"SkillParentWhereUniqueInput"
	},
	SkillParentCreateOneInlineInput:{
		create:"SkillParentCreateInput",
		connect:"SkillParentWhereUniqueInput"
	},
	SkillParentUpdateInput:{
		SkillCategory:"SkillCategoryUpdateInput"
	},
	SkillParentUpdateManyInlineInput:{
		create:"SkillParentCreateInput",
		connect:"SkillParentConnectInput",
		set:"SkillParentWhereUniqueInput",
		update:"SkillParentUpdateWithNestedWhereUniqueInput",
		upsert:"SkillParentUpsertWithNestedWhereUniqueInput",
		disconnect:"SkillParentWhereUniqueInput",
		delete:"SkillParentWhereUniqueInput"
	},
	SkillParentUpdateManyWithNestedWhereInput:{
		SkillCategory:"SkillCategoryUpdateManyWithNestedWhereInput"
	},
	SkillParentUpdateOneInlineInput:{
		create:"SkillParentCreateInput",
		update:"SkillParentUpdateWithNestedWhereUniqueInput",
		upsert:"SkillParentUpsertWithNestedWhereUniqueInput",
		connect:"SkillParentWhereUniqueInput"
	},
	SkillParentUpdateWithNestedWhereUniqueInput:{
		SkillCategory:"SkillCategoryUpdateWithNestedWhereUniqueInput"
	},
	SkillParentUpsertWithNestedWhereUniqueInput:{
		SkillCategory:"SkillCategoryUpsertWithNestedWhereUniqueInput"
	},
	SkillParentWhereInput:{
		SkillCategory:"SkillCategoryWhereInput"
	},
	SkillParentWhereUniqueInput:{
		SkillCategory:"SkillCategoryWhereUniqueInput"
	},
	SkillUpdateInput:{
		icon:"AssetUpdateOneInlineInput"
	},
	SkillUpdateManyInlineInput:{
		create:"SkillCreateWithPositionInput",
		update:"SkillUpdateWithNestedWhereUniqueAndPositionInput",
		upsert:"SkillUpsertWithNestedWhereUniqueAndPositionInput",
		delete:"SkillWhereUniqueInput"
	},
	SkillUpdateManyInput:{

	},
	SkillUpdateManyWithNestedWhereInput:{
		where:"SkillWhereInput",
		data:"SkillUpdateManyInput"
	},
	SkillUpdateOneInlineInput:{
		create:"SkillCreateInput",
		update:"SkillUpdateWithNestedWhereUniqueInput",
		upsert:"SkillUpsertWithNestedWhereUniqueInput"
	},
	SkillUpdateWithNestedWhereUniqueAndPositionInput:{
		where:"SkillWhereUniqueInput",
		position:"ConnectPositionInput",
		data:"SkillUpdateInput"
	},
	SkillUpdateWithNestedWhereUniqueInput:{
		where:"SkillWhereUniqueInput",
		data:"SkillUpdateInput"
	},
	SkillUpsertInput:{
		create:"SkillCreateInput",
		update:"SkillUpdateInput"
	},
	SkillUpsertWithNestedWhereUniqueAndPositionInput:{
		where:"SkillWhereUniqueInput",
		position:"ConnectPositionInput",
		data:"SkillUpsertInput"
	},
	SkillUpsertWithNestedWhereUniqueInput:{
		where:"SkillWhereUniqueInput",
		data:"SkillUpsertInput"
	},
	SkillWhereInput:{
		AND:"SkillWhereInput",
		OR:"SkillWhereInput",
		NOT:"SkillWhereInput",
		icon:"AssetWhereInput"
	},
	SkillWhereUniqueInput:{

	},
	Stage: "enum" as const,
	SystemDateTimeFieldVariation: "enum" as const,
	Technologies: "enum" as const,
	UnpublishLocaleInput:{
		locale:"Locale",
		stages:"Stage"
	},
	User:{
		documentInStages:{
			stages:"Stage"
		}
	},
	UserConnectInput:{
		where:"UserWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	UserCreateManyInlineInput:{
		connect:"UserWhereUniqueInput"
	},
	UserCreateOneInlineInput:{
		connect:"UserWhereUniqueInput"
	},
	UserKind: "enum" as const,
	UserManyWhereInput:{
		AND:"UserWhereInput",
		OR:"UserWhereInput",
		NOT:"UserWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		kind:"UserKind",
		kind_not:"UserKind",
		kind_in:"UserKind",
		kind_not_in:"UserKind"
	},
	UserOrderByInput: "enum" as const,
	UserUpdateManyInlineInput:{
		connect:"UserConnectInput",
		set:"UserWhereUniqueInput",
		disconnect:"UserWhereUniqueInput"
	},
	UserUpdateOneInlineInput:{
		connect:"UserWhereUniqueInput"
	},
	UserWhereInput:{
		AND:"UserWhereInput",
		OR:"UserWhereInput",
		NOT:"UserWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		kind:"UserKind",
		kind_not:"UserKind",
		kind_in:"UserKind",
		kind_not_in:"UserKind"
	},
	UserWhereUniqueInput:{

	},
	VersionWhereInput:{
		stage:"Stage"
	},
	_FilterKind: "enum" as const,
	_MutationInputFieldKind: "enum" as const,
	_MutationKind: "enum" as const,
	_OrderDirection: "enum" as const,
	_RelationInputCardinality: "enum" as const,
	_RelationInputKind: "enum" as const,
	_RelationKind: "enum" as const,
	_SystemDateTimeFieldVariation: "enum" as const
}

export const ReturnTypes: Record<string,any> = {
	AboutMe:{
		stage:"Stage",
		documentInStages:"AboutMe",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		contactEmail:"String",
		description:"String",
		company:"Company",
		links:"AboutMelinksUnion",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		photo:"Asset",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	AboutMeConnection:{
		pageInfo:"PageInfo",
		edges:"AboutMeEdge",
		aggregate:"Aggregate"
	},
	AboutMeEdge:{
		node:"AboutMe",
		cursor:"String"
	},
	AboutMelinksUnion:{
		"...on Link":"Link"
	},
	Aggregate:{
		count:"Int"
	},
	Asset:{
		stage:"Stage",
		locale:"Locale",
		localizations:"Asset",
		documentInStages:"Asset",
		mimeType:"String",
		size:"Float",
		width:"Float",
		height:"Float",
		fileName:"String",
		handle:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		imageProject:"Project",
		og_imageSeo:"Seo",
		photoAboutMe:"AboutMe",
		scheduledIn:"ScheduledOperation",
		history:"Version",
		url:"String"
	},
	AssetConnection:{
		pageInfo:"PageInfo",
		edges:"AssetEdge",
		aggregate:"Aggregate"
	},
	AssetEdge:{
		node:"Asset",
		cursor:"String"
	},
	BatchPayload:{
		count:"Long"
	},
	Color:{
		hex:"Hex",
		rgba:"RGBA",
		css:"String"
	},
	Company:{
		stage:"Stage",
		id:"ID",
		companyName:"String",
		companyWebsite:"String"
	},
	CompanyConnection:{
		pageInfo:"PageInfo",
		edges:"CompanyEdge",
		aggregate:"Aggregate"
	},
	CompanyEdge:{
		node:"Company",
		cursor:"String"
	},
	CompanyParent:{
		"...on AboutMe":"AboutMe"
	},
	Date: `scalar.Date` as const,
	DateTime: `scalar.DateTime` as const,
	DocumentVersion:{
		id:"ID",
		stage:"Stage",
		revision:"Int",
		createdAt:"DateTime",
		data:"Json"
	},
	Hex: `scalar.Hex` as const,
	Json: `scalar.Json` as const,
	Link:{
		stage:"Stage",
		id:"ID",
		name:"String",
		url:"String",
		icon:"Asset"
	},
	LinkConnection:{
		pageInfo:"PageInfo",
		edges:"LinkEdge",
		aggregate:"Aggregate"
	},
	LinkEdge:{
		node:"Link",
		cursor:"String"
	},
	LinkParent:{
		"...on AboutMe":"AboutMe"
	},
	Location:{
		latitude:"Float",
		longitude:"Float",
		distance:"Float"
	},
	Long: `scalar.Long` as const,
	Mutation:{
		createAsset:"Asset",
		updateAsset:"Asset",
		deleteAsset:"Asset",
		upsertAsset:"Asset",
		publishAsset:"Asset",
		unpublishAsset:"Asset",
		updateManyAssetsConnection:"AssetConnection",
		deleteManyAssetsConnection:"AssetConnection",
		publishManyAssetsConnection:"AssetConnection",
		unpublishManyAssetsConnection:"AssetConnection",
		updateManyAssets:"BatchPayload",
		deleteManyAssets:"BatchPayload",
		publishManyAssets:"BatchPayload",
		unpublishManyAssets:"BatchPayload",
		schedulePublishAsset:"Asset",
		scheduleUnpublishAsset:"Asset",
		deleteScheduledOperation:"ScheduledOperation",
		createScheduledRelease:"ScheduledRelease",
		updateScheduledRelease:"ScheduledRelease",
		deleteScheduledRelease:"ScheduledRelease",
		createProject:"Project",
		updateProject:"Project",
		deleteProject:"Project",
		upsertProject:"Project",
		publishProject:"Project",
		unpublishProject:"Project",
		updateManyProjectsConnection:"ProjectConnection",
		deleteManyProjectsConnection:"ProjectConnection",
		publishManyProjectsConnection:"ProjectConnection",
		unpublishManyProjectsConnection:"ProjectConnection",
		updateManyProjects:"BatchPayload",
		deleteManyProjects:"BatchPayload",
		publishManyProjects:"BatchPayload",
		unpublishManyProjects:"BatchPayload",
		schedulePublishProject:"Project",
		scheduleUnpublishProject:"Project",
		createSeo:"Seo",
		updateSeo:"Seo",
		deleteSeo:"Seo",
		upsertSeo:"Seo",
		publishSeo:"Seo",
		unpublishSeo:"Seo",
		updateManySeosConnection:"SeoConnection",
		deleteManySeosConnection:"SeoConnection",
		publishManySeosConnection:"SeoConnection",
		unpublishManySeosConnection:"SeoConnection",
		updateManySeos:"BatchPayload",
		deleteManySeos:"BatchPayload",
		publishManySeos:"BatchPayload",
		unpublishManySeos:"BatchPayload",
		schedulePublishSeo:"Seo",
		scheduleUnpublishSeo:"Seo",
		createAboutMe:"AboutMe",
		updateAboutMe:"AboutMe",
		deleteAboutMe:"AboutMe",
		upsertAboutMe:"AboutMe",
		publishAboutMe:"AboutMe",
		unpublishAboutMe:"AboutMe",
		updateManyAboutMesConnection:"AboutMeConnection",
		deleteManyAboutMesConnection:"AboutMeConnection",
		publishManyAboutMesConnection:"AboutMeConnection",
		unpublishManyAboutMesConnection:"AboutMeConnection",
		updateManyAboutMes:"BatchPayload",
		deleteManyAboutMes:"BatchPayload",
		publishManyAboutMes:"BatchPayload",
		unpublishManyAboutMes:"BatchPayload",
		schedulePublishAboutMe:"AboutMe",
		scheduleUnpublishAboutMe:"AboutMe",
		createSkillCategory:"SkillCategory",
		updateSkillCategory:"SkillCategory",
		deleteSkillCategory:"SkillCategory",
		upsertSkillCategory:"SkillCategory",
		publishSkillCategory:"SkillCategory",
		unpublishSkillCategory:"SkillCategory",
		updateManySkillCategoriesConnection:"SkillCategoryConnection",
		deleteManySkillCategoriesConnection:"SkillCategoryConnection",
		publishManySkillCategoriesConnection:"SkillCategoryConnection",
		unpublishManySkillCategoriesConnection:"SkillCategoryConnection",
		updateManySkillCategories:"BatchPayload",
		deleteManySkillCategories:"BatchPayload",
		publishManySkillCategories:"BatchPayload",
		unpublishManySkillCategories:"BatchPayload",
		schedulePublishSkillCategory:"SkillCategory",
		scheduleUnpublishSkillCategory:"SkillCategory"
	},
	Node:{
		"...on AboutMe": "AboutMe",
		"...on Asset": "Asset",
		"...on Project": "Project",
		"...on ScheduledOperation": "ScheduledOperation",
		"...on ScheduledRelease": "ScheduledRelease",
		"...on Seo": "Seo",
		"...on SkillCategory": "SkillCategory",
		"...on User": "User",
		id:"ID",
		stage:"Stage"
	},
	PageInfo:{
		hasNextPage:"Boolean",
		hasPreviousPage:"Boolean",
		startCursor:"String",
		endCursor:"String",
		pageSize:"Int"
	},
	Project:{
		stage:"Stage",
		documentInStages:"Project",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		name:"String",
		description:"String",
		demo:"String",
		sourceCode:"String",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		image:"Asset",
		stack:"Technologies",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	ProjectConnection:{
		pageInfo:"PageInfo",
		edges:"ProjectEdge",
		aggregate:"Aggregate"
	},
	ProjectEdge:{
		node:"Project",
		cursor:"String"
	},
	Query:{
		node:"Node",
		users:"User",
		user:"User",
		usersConnection:"UserConnection",
		assets:"Asset",
		asset:"Asset",
		assetsConnection:"AssetConnection",
		assetVersion:"DocumentVersion",
		scheduledOperations:"ScheduledOperation",
		scheduledOperation:"ScheduledOperation",
		scheduledOperationsConnection:"ScheduledOperationConnection",
		scheduledReleases:"ScheduledRelease",
		scheduledRelease:"ScheduledRelease",
		scheduledReleasesConnection:"ScheduledReleaseConnection",
		projects:"Project",
		project:"Project",
		projectsConnection:"ProjectConnection",
		projectVersion:"DocumentVersion",
		seos:"Seo",
		seo:"Seo",
		seosConnection:"SeoConnection",
		seoVersion:"DocumentVersion",
		aboutMes:"AboutMe",
		aboutMe:"AboutMe",
		aboutMesConnection:"AboutMeConnection",
		aboutMeVersion:"DocumentVersion",
		skillCategories:"SkillCategory",
		skillCategory:"SkillCategory",
		skillCategoriesConnection:"SkillCategoryConnection",
		skillCategoryVersion:"DocumentVersion"
	},
	RGBA:{
		r:"RGBAHue",
		g:"RGBAHue",
		b:"RGBAHue",
		a:"RGBATransparency"
	},
	RGBAHue: `scalar.RGBAHue` as const,
	RGBATransparency: `scalar.RGBATransparency` as const,
	RichText:{
		raw:"RichTextAST",
		html:"String",
		markdown:"String",
		text:"String"
	},
	RichTextAST: `scalar.RichTextAST` as const,
	ScheduledOperation:{
		stage:"Stage",
		documentInStages:"ScheduledOperation",
		rawPayload:"Json",
		errorMessage:"String",
		description:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		release:"ScheduledRelease",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		status:"ScheduledOperationStatus",
		affectedDocuments:"ScheduledOperationAffectedDocument"
	},
	ScheduledOperationAffectedDocument:{
		"...on AboutMe":"AboutMe",
		"...on Asset":"Asset",
		"...on Project":"Project",
		"...on Seo":"Seo",
		"...on SkillCategory":"SkillCategory"
	},
	ScheduledOperationConnection:{
		pageInfo:"PageInfo",
		edges:"ScheduledOperationEdge",
		aggregate:"Aggregate"
	},
	ScheduledOperationEdge:{
		node:"ScheduledOperation",
		cursor:"String"
	},
	ScheduledRelease:{
		stage:"Stage",
		documentInStages:"ScheduledRelease",
		releaseAt:"DateTime",
		isImplicit:"Boolean",
		isActive:"Boolean",
		errorMessage:"String",
		description:"String",
		title:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		operations:"ScheduledOperation",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		status:"ScheduledReleaseStatus"
	},
	ScheduledReleaseConnection:{
		pageInfo:"PageInfo",
		edges:"ScheduledReleaseEdge",
		aggregate:"Aggregate"
	},
	ScheduledReleaseEdge:{
		node:"ScheduledRelease",
		cursor:"String"
	},
	Seo:{
		stage:"Stage",
		documentInStages:"Seo",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		title:"String",
		description:"String",
		keywords:"String",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		og_image:"Asset",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	SeoConnection:{
		pageInfo:"PageInfo",
		edges:"SeoEdge",
		aggregate:"Aggregate"
	},
	SeoEdge:{
		node:"Seo",
		cursor:"String"
	},
	Skill:{
		stage:"Stage",
		id:"ID",
		name:"String",
		icon:"Asset"
	},
	SkillCategory:{
		stage:"Stage",
		documentInStages:"SkillCategory",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		name:"String",
		skillsList:"SkillCategoryskillsListUnion",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	SkillCategoryConnection:{
		pageInfo:"PageInfo",
		edges:"SkillCategoryEdge",
		aggregate:"Aggregate"
	},
	SkillCategoryEdge:{
		node:"SkillCategory",
		cursor:"String"
	},
	SkillCategoryskillsListUnion:{
		"...on Skill":"Skill"
	},
	SkillConnection:{
		pageInfo:"PageInfo",
		edges:"SkillEdge",
		aggregate:"Aggregate"
	},
	SkillEdge:{
		node:"Skill",
		cursor:"String"
	},
	SkillParent:{
		"...on SkillCategory":"SkillCategory"
	},
	User:{
		stage:"Stage",
		documentInStages:"User",
		isActive:"Boolean",
		picture:"String",
		name:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		kind:"UserKind"
	},
	UserConnection:{
		pageInfo:"PageInfo",
		edges:"UserEdge",
		aggregate:"Aggregate"
	},
	UserEdge:{
		node:"User",
		cursor:"String"
	},
	Version:{
		id:"ID",
		stage:"Stage",
		revision:"Int",
		createdAt:"DateTime"
	}
}

export const Ops = {
mutation: "Mutation" as const,
	query: "Query" as const
}