/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Asset:{
		localizations:{
			locales:"Locale"
		},
		documentInStages:{
			stages:"Stage"
		},
		publishedAt:{
			variation:"SystemDateTimeFieldVariation"
		},
		updatedAt:{
			variation:"SystemDateTimeFieldVariation"
		},
		createdAt:{
			variation:"SystemDateTimeFieldVariation"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		imageProject:{
			where:"ProjectWhereInput",
			orderBy:"ProjectOrderByInput",
			locales:"Locale"
		},
		imageSocial:{
			where:"SocialWhereInput",
			orderBy:"SocialOrderByInput",
			locales:"Locale"
		},
		imagePageMetadata:{
			where:"PageMetadataWhereInput",
			orderBy:"PageMetadataOrderByInput",
			locales:"Locale"
		},
		iconSkill:{
			where:"SkillWhereInput",
			orderBy:"SkillOrderByInput",
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		},
		url:{
			transformation:"AssetTransformationInput"
		}
	},
	AssetConnectInput:{
		where:"AssetWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	AssetCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		imageProject:"ProjectCreateManyInlineInput",
		imageSocial:"SocialCreateManyInlineInput",
		imagePageMetadata:"PageMetadataCreateManyInlineInput",
		iconSkill:"SkillCreateManyInlineInput",
		localizations:"AssetCreateLocalizationsInput"
	},
	AssetCreateLocalizationDataInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime"
	},
	AssetCreateLocalizationInput:{
		data:"AssetCreateLocalizationDataInput",
		locale:"Locale"
	},
	AssetCreateLocalizationsInput:{
		create:"AssetCreateLocalizationInput"
	},
	AssetCreateManyInlineInput:{
		create:"AssetCreateInput",
		connect:"AssetWhereUniqueInput"
	},
	AssetCreateOneInlineInput:{
		create:"AssetCreateInput",
		connect:"AssetWhereUniqueInput"
	},
	AssetManyWhereInput:{
		AND:"AssetWhereInput",
		OR:"AssetWhereInput",
		NOT:"AssetWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		imageProject_every:"ProjectWhereInput",
		imageProject_some:"ProjectWhereInput",
		imageProject_none:"ProjectWhereInput",
		imageSocial_every:"SocialWhereInput",
		imageSocial_some:"SocialWhereInput",
		imageSocial_none:"SocialWhereInput",
		imagePageMetadata_every:"PageMetadataWhereInput",
		imagePageMetadata_some:"PageMetadataWhereInput",
		imagePageMetadata_none:"PageMetadataWhereInput",
		iconSkill_every:"SkillWhereInput",
		iconSkill_some:"SkillWhereInput",
		iconSkill_none:"SkillWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	AssetOrderByInput: "enum" as const,
	AssetTransformationInput:{
		image:"ImageTransformationInput",
		document:"DocumentTransformationInput"
	},
	AssetUpdateInput:{
		imageProject:"ProjectUpdateManyInlineInput",
		imageSocial:"SocialUpdateManyInlineInput",
		imagePageMetadata:"PageMetadataUpdateManyInlineInput",
		iconSkill:"SkillUpdateManyInlineInput",
		localizations:"AssetUpdateLocalizationsInput"
	},
	AssetUpdateLocalizationDataInput:{

	},
	AssetUpdateLocalizationInput:{
		data:"AssetUpdateLocalizationDataInput",
		locale:"Locale"
	},
	AssetUpdateLocalizationsInput:{
		create:"AssetCreateLocalizationInput",
		update:"AssetUpdateLocalizationInput",
		upsert:"AssetUpsertLocalizationInput",
		delete:"Locale"
	},
	AssetUpdateManyInlineInput:{
		create:"AssetCreateInput",
		connect:"AssetConnectInput",
		set:"AssetWhereUniqueInput",
		update:"AssetUpdateWithNestedWhereUniqueInput",
		upsert:"AssetUpsertWithNestedWhereUniqueInput",
		disconnect:"AssetWhereUniqueInput",
		delete:"AssetWhereUniqueInput"
	},
	AssetUpdateManyInput:{
		localizations:"AssetUpdateManyLocalizationsInput"
	},
	AssetUpdateManyLocalizationDataInput:{

	},
	AssetUpdateManyLocalizationInput:{
		data:"AssetUpdateManyLocalizationDataInput",
		locale:"Locale"
	},
	AssetUpdateManyLocalizationsInput:{
		update:"AssetUpdateManyLocalizationInput"
	},
	AssetUpdateManyWithNestedWhereInput:{
		where:"AssetWhereInput",
		data:"AssetUpdateManyInput"
	},
	AssetUpdateOneInlineInput:{
		create:"AssetCreateInput",
		update:"AssetUpdateWithNestedWhereUniqueInput",
		upsert:"AssetUpsertWithNestedWhereUniqueInput",
		connect:"AssetWhereUniqueInput"
	},
	AssetUpdateWithNestedWhereUniqueInput:{
		where:"AssetWhereUniqueInput",
		data:"AssetUpdateInput"
	},
	AssetUpsertInput:{
		create:"AssetCreateInput",
		update:"AssetUpdateInput"
	},
	AssetUpsertLocalizationInput:{
		update:"AssetUpdateLocalizationDataInput",
		create:"AssetCreateLocalizationDataInput",
		locale:"Locale"
	},
	AssetUpsertWithNestedWhereUniqueInput:{
		where:"AssetWhereUniqueInput",
		data:"AssetUpsertInput"
	},
	AssetWhereInput:{
		AND:"AssetWhereInput",
		OR:"AssetWhereInput",
		NOT:"AssetWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		imageProject_every:"ProjectWhereInput",
		imageProject_some:"ProjectWhereInput",
		imageProject_none:"ProjectWhereInput",
		imageSocial_every:"SocialWhereInput",
		imageSocial_some:"SocialWhereInput",
		imageSocial_none:"SocialWhereInput",
		imagePageMetadata_every:"PageMetadataWhereInput",
		imagePageMetadata_some:"PageMetadataWhereInput",
		imagePageMetadata_none:"PageMetadataWhereInput",
		iconSkill_every:"SkillWhereInput",
		iconSkill_some:"SkillWhereInput",
		iconSkill_none:"SkillWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	AssetWhereUniqueInput:{

	},
	ColorInput:{
		hex:"Hex",
		rgba:"RGBAInput"
	},
	ConnectPositionInput:{

	},
	Date: `scalar.Date` as const,
	DateTime: `scalar.DateTime` as const,
	DocumentFileTypes: "enum" as const,
	DocumentOutputInput:{
		format:"DocumentFileTypes"
	},
	DocumentTransformationInput:{
		output:"DocumentOutputInput"
	},
	Hex: `scalar.Hex` as const,
	ImageFit: "enum" as const,
	ImageResizeInput:{
		fit:"ImageFit"
	},
	ImageTransformationInput:{
		resize:"ImageResizeInput"
	},
	Json: `scalar.Json` as const,
	Locale: "enum" as const,
	Location:{
		distance:{
			from:"LocationInput"
		}
	},
	LocationInput:{

	},
	Long: `scalar.Long` as const,
	Mutation:{
		createAsset:{
			data:"AssetCreateInput"
		},
		updateAsset:{
			where:"AssetWhereUniqueInput",
			data:"AssetUpdateInput"
		},
		deleteAsset:{
			where:"AssetWhereUniqueInput"
		},
		upsertAsset:{
			where:"AssetWhereUniqueInput",
			upsert:"AssetUpsertInput"
		},
		publishAsset:{
			where:"AssetWhereUniqueInput",
			locales:"Locale",
			to:"Stage"
		},
		unpublishAsset:{
			where:"AssetWhereUniqueInput",
			from:"Stage",
			locales:"Locale"
		},
		updateManyAssetsConnection:{
			where:"AssetManyWhereInput",
			data:"AssetUpdateManyInput"
		},
		deleteManyAssetsConnection:{
			where:"AssetManyWhereInput"
		},
		publishManyAssetsConnection:{
			where:"AssetManyWhereInput",
			from:"Stage",
			to:"Stage",
			locales:"Locale"
		},
		unpublishManyAssetsConnection:{
			where:"AssetManyWhereInput",
			stage:"Stage",
			from:"Stage",
			locales:"Locale"
		},
		updateManyAssets:{
			where:"AssetManyWhereInput",
			data:"AssetUpdateManyInput"
		},
		deleteManyAssets:{
			where:"AssetManyWhereInput"
		},
		publishManyAssets:{
			where:"AssetManyWhereInput",
			to:"Stage",
			locales:"Locale"
		},
		unpublishManyAssets:{
			where:"AssetManyWhereInput",
			from:"Stage",
			locales:"Locale"
		},
		schedulePublishAsset:{
			where:"AssetWhereUniqueInput",
			locales:"Locale",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishAsset:{
			where:"AssetWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime",
			locales:"Locale"
		},
		deleteScheduledOperation:{
			where:"ScheduledOperationWhereUniqueInput"
		},
		createScheduledRelease:{
			data:"ScheduledReleaseCreateInput"
		},
		updateScheduledRelease:{
			where:"ScheduledReleaseWhereUniqueInput",
			data:"ScheduledReleaseUpdateInput"
		},
		deleteScheduledRelease:{
			where:"ScheduledReleaseWhereUniqueInput"
		},
		createProject:{
			data:"ProjectCreateInput"
		},
		updateProject:{
			where:"ProjectWhereUniqueInput",
			data:"ProjectUpdateInput"
		},
		deleteProject:{
			where:"ProjectWhereUniqueInput"
		},
		upsertProject:{
			where:"ProjectWhereUniqueInput",
			upsert:"ProjectUpsertInput"
		},
		publishProject:{
			where:"ProjectWhereUniqueInput",
			to:"Stage"
		},
		unpublishProject:{
			where:"ProjectWhereUniqueInput",
			from:"Stage"
		},
		updateManyProjectsConnection:{
			where:"ProjectManyWhereInput",
			data:"ProjectUpdateManyInput"
		},
		deleteManyProjectsConnection:{
			where:"ProjectManyWhereInput"
		},
		publishManyProjectsConnection:{
			where:"ProjectManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManyProjectsConnection:{
			where:"ProjectManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManyProjects:{
			where:"ProjectManyWhereInput",
			data:"ProjectUpdateManyInput"
		},
		deleteManyProjects:{
			where:"ProjectManyWhereInput"
		},
		publishManyProjects:{
			where:"ProjectManyWhereInput",
			to:"Stage"
		},
		unpublishManyProjects:{
			where:"ProjectManyWhereInput",
			from:"Stage"
		},
		schedulePublishProject:{
			where:"ProjectWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishProject:{
			where:"ProjectWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		},
		createSocial:{
			data:"SocialCreateInput"
		},
		updateSocial:{
			where:"SocialWhereUniqueInput",
			data:"SocialUpdateInput"
		},
		deleteSocial:{
			where:"SocialWhereUniqueInput"
		},
		upsertSocial:{
			where:"SocialWhereUniqueInput",
			upsert:"SocialUpsertInput"
		},
		publishSocial:{
			where:"SocialWhereUniqueInput",
			to:"Stage"
		},
		unpublishSocial:{
			where:"SocialWhereUniqueInput",
			from:"Stage"
		},
		updateManySocialsConnection:{
			where:"SocialManyWhereInput",
			data:"SocialUpdateManyInput"
		},
		deleteManySocialsConnection:{
			where:"SocialManyWhereInput"
		},
		publishManySocialsConnection:{
			where:"SocialManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManySocialsConnection:{
			where:"SocialManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManySocials:{
			where:"SocialManyWhereInput",
			data:"SocialUpdateManyInput"
		},
		deleteManySocials:{
			where:"SocialManyWhereInput"
		},
		publishManySocials:{
			where:"SocialManyWhereInput",
			to:"Stage"
		},
		unpublishManySocials:{
			where:"SocialManyWhereInput",
			from:"Stage"
		},
		schedulePublishSocial:{
			where:"SocialWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishSocial:{
			where:"SocialWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		},
		createPageMetadata:{
			data:"PageMetadataCreateInput"
		},
		updatePageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			data:"PageMetadataUpdateInput"
		},
		deletePageMetadata:{
			where:"PageMetadataWhereUniqueInput"
		},
		upsertPageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			upsert:"PageMetadataUpsertInput"
		},
		publishPageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			to:"Stage"
		},
		unpublishPageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			from:"Stage"
		},
		updateManyPagesMetadataConnection:{
			where:"PageMetadataManyWhereInput",
			data:"PageMetadataUpdateManyInput"
		},
		deleteManyPagesMetadataConnection:{
			where:"PageMetadataManyWhereInput"
		},
		publishManyPagesMetadataConnection:{
			where:"PageMetadataManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManyPagesMetadataConnection:{
			where:"PageMetadataManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManyPagesMetadata:{
			where:"PageMetadataManyWhereInput",
			data:"PageMetadataUpdateManyInput"
		},
		deleteManyPagesMetadata:{
			where:"PageMetadataManyWhereInput"
		},
		publishManyPagesMetadata:{
			where:"PageMetadataManyWhereInput",
			to:"Stage"
		},
		unpublishManyPagesMetadata:{
			where:"PageMetadataManyWhereInput",
			from:"Stage"
		},
		schedulePublishPageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishPageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		},
		createSkill:{
			data:"SkillCreateInput"
		},
		updateSkill:{
			where:"SkillWhereUniqueInput",
			data:"SkillUpdateInput"
		},
		deleteSkill:{
			where:"SkillWhereUniqueInput"
		},
		upsertSkill:{
			where:"SkillWhereUniqueInput",
			upsert:"SkillUpsertInput"
		},
		publishSkill:{
			where:"SkillWhereUniqueInput",
			to:"Stage"
		},
		unpublishSkill:{
			where:"SkillWhereUniqueInput",
			from:"Stage"
		},
		updateManySkillsConnection:{
			where:"SkillManyWhereInput",
			data:"SkillUpdateManyInput"
		},
		deleteManySkillsConnection:{
			where:"SkillManyWhereInput"
		},
		publishManySkillsConnection:{
			where:"SkillManyWhereInput",
			from:"Stage",
			to:"Stage"
		},
		unpublishManySkillsConnection:{
			where:"SkillManyWhereInput",
			stage:"Stage",
			from:"Stage"
		},
		updateManySkills:{
			where:"SkillManyWhereInput",
			data:"SkillUpdateManyInput"
		},
		deleteManySkills:{
			where:"SkillManyWhereInput"
		},
		publishManySkills:{
			where:"SkillManyWhereInput",
			to:"Stage"
		},
		unpublishManySkills:{
			where:"SkillManyWhereInput",
			from:"Stage"
		},
		schedulePublishSkill:{
			where:"SkillWhereUniqueInput",
			to:"Stage",
			releaseAt:"DateTime"
		},
		scheduleUnpublishSkill:{
			where:"SkillWhereUniqueInput",
			from:"Stage",
			releaseAt:"DateTime"
		}
	},
	PageMetadata:{
		documentInStages:{
			stages:"Stage"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		image:{
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	PageMetadataConnectInput:{
		where:"PageMetadataWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	PageMetadataCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		image:"AssetCreateOneInlineInput"
	},
	PageMetadataCreateManyInlineInput:{
		create:"PageMetadataCreateInput",
		connect:"PageMetadataWhereUniqueInput"
	},
	PageMetadataCreateOneInlineInput:{
		create:"PageMetadataCreateInput",
		connect:"PageMetadataWhereUniqueInput"
	},
	PageMetadataManyWhereInput:{
		AND:"PageMetadataWhereInput",
		OR:"PageMetadataWhereInput",
		NOT:"PageMetadataWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	PageMetadataOrderByInput: "enum" as const,
	PageMetadataUpdateInput:{
		image:"AssetUpdateOneInlineInput"
	},
	PageMetadataUpdateManyInlineInput:{
		create:"PageMetadataCreateInput",
		connect:"PageMetadataConnectInput",
		set:"PageMetadataWhereUniqueInput",
		update:"PageMetadataUpdateWithNestedWhereUniqueInput",
		upsert:"PageMetadataUpsertWithNestedWhereUniqueInput",
		disconnect:"PageMetadataWhereUniqueInput",
		delete:"PageMetadataWhereUniqueInput"
	},
	PageMetadataUpdateManyInput:{

	},
	PageMetadataUpdateManyWithNestedWhereInput:{
		where:"PageMetadataWhereInput",
		data:"PageMetadataUpdateManyInput"
	},
	PageMetadataUpdateOneInlineInput:{
		create:"PageMetadataCreateInput",
		update:"PageMetadataUpdateWithNestedWhereUniqueInput",
		upsert:"PageMetadataUpsertWithNestedWhereUniqueInput",
		connect:"PageMetadataWhereUniqueInput"
	},
	PageMetadataUpdateWithNestedWhereUniqueInput:{
		where:"PageMetadataWhereUniqueInput",
		data:"PageMetadataUpdateInput"
	},
	PageMetadataUpsertInput:{
		create:"PageMetadataCreateInput",
		update:"PageMetadataUpdateInput"
	},
	PageMetadataUpsertWithNestedWhereUniqueInput:{
		where:"PageMetadataWhereUniqueInput",
		data:"PageMetadataUpsertInput"
	},
	PageMetadataWhereInput:{
		AND:"PageMetadataWhereInput",
		OR:"PageMetadataWhereInput",
		NOT:"PageMetadataWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	PageMetadataWhereUniqueInput:{

	},
	Project:{
		documentInStages:{
			stages:"Stage"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		image:{
			where:"AssetWhereInput",
			orderBy:"AssetOrderByInput",
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	ProjectConnectInput:{
		where:"ProjectWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	ProjectCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		image:"AssetCreateManyInlineInput"
	},
	ProjectCreateManyInlineInput:{
		create:"ProjectCreateInput",
		connect:"ProjectWhereUniqueInput"
	},
	ProjectCreateOneInlineInput:{
		create:"ProjectCreateInput",
		connect:"ProjectWhereUniqueInput"
	},
	ProjectManyWhereInput:{
		AND:"ProjectWhereInput",
		OR:"ProjectWhereInput",
		NOT:"ProjectWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image_every:"AssetWhereInput",
		image_some:"AssetWhereInput",
		image_none:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	ProjectOrderByInput: "enum" as const,
	ProjectUpdateInput:{
		image:"AssetUpdateManyInlineInput"
	},
	ProjectUpdateManyInlineInput:{
		create:"ProjectCreateInput",
		connect:"ProjectConnectInput",
		set:"ProjectWhereUniqueInput",
		update:"ProjectUpdateWithNestedWhereUniqueInput",
		upsert:"ProjectUpsertWithNestedWhereUniqueInput",
		disconnect:"ProjectWhereUniqueInput",
		delete:"ProjectWhereUniqueInput"
	},
	ProjectUpdateManyInput:{

	},
	ProjectUpdateManyWithNestedWhereInput:{
		where:"ProjectWhereInput",
		data:"ProjectUpdateManyInput"
	},
	ProjectUpdateOneInlineInput:{
		create:"ProjectCreateInput",
		update:"ProjectUpdateWithNestedWhereUniqueInput",
		upsert:"ProjectUpsertWithNestedWhereUniqueInput",
		connect:"ProjectWhereUniqueInput"
	},
	ProjectUpdateWithNestedWhereUniqueInput:{
		where:"ProjectWhereUniqueInput",
		data:"ProjectUpdateInput"
	},
	ProjectUpsertInput:{
		create:"ProjectCreateInput",
		update:"ProjectUpdateInput"
	},
	ProjectUpsertWithNestedWhereUniqueInput:{
		where:"ProjectWhereUniqueInput",
		data:"ProjectUpsertInput"
	},
	ProjectWhereInput:{
		AND:"ProjectWhereInput",
		OR:"ProjectWhereInput",
		NOT:"ProjectWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image_every:"AssetWhereInput",
		image_some:"AssetWhereInput",
		image_none:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	ProjectWhereUniqueInput:{

	},
	PublishLocaleInput:{
		locale:"Locale",
		stages:"Stage"
	},
	Query:{
		node:{
			stage:"Stage",
			locales:"Locale"
		},
		users:{
			where:"UserWhereInput",
			orderBy:"UserOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		user:{
			where:"UserWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		usersConnection:{
			where:"UserWhereInput",
			orderBy:"UserOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		assets:{
			where:"AssetWhereInput",
			orderBy:"AssetOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		asset:{
			where:"AssetWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		assetsConnection:{
			where:"AssetWhereInput",
			orderBy:"AssetOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		assetVersion:{
			where:"VersionWhereInput"
		},
		scheduledOperations:{
			where:"ScheduledOperationWhereInput",
			orderBy:"ScheduledOperationOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledOperation:{
			where:"ScheduledOperationWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledOperationsConnection:{
			where:"ScheduledOperationWhereInput",
			orderBy:"ScheduledOperationOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledReleases:{
			where:"ScheduledReleaseWhereInput",
			orderBy:"ScheduledReleaseOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledRelease:{
			where:"ScheduledReleaseWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		scheduledReleasesConnection:{
			where:"ScheduledReleaseWhereInput",
			orderBy:"ScheduledReleaseOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		projects:{
			where:"ProjectWhereInput",
			orderBy:"ProjectOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		project:{
			where:"ProjectWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		projectsConnection:{
			where:"ProjectWhereInput",
			orderBy:"ProjectOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		projectVersion:{
			where:"VersionWhereInput"
		},
		socials:{
			where:"SocialWhereInput",
			orderBy:"SocialOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		social:{
			where:"SocialWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		socialsConnection:{
			where:"SocialWhereInput",
			orderBy:"SocialOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		socialVersion:{
			where:"VersionWhereInput"
		},
		pagesMetadata:{
			where:"PageMetadataWhereInput",
			orderBy:"PageMetadataOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		pageMetadata:{
			where:"PageMetadataWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		pagesMetadataConnection:{
			where:"PageMetadataWhereInput",
			orderBy:"PageMetadataOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		pageMetadataVersion:{
			where:"VersionWhereInput"
		},
		skills:{
			where:"SkillWhereInput",
			orderBy:"SkillOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		skill:{
			where:"SkillWhereUniqueInput",
			stage:"Stage",
			locales:"Locale"
		},
		skillsConnection:{
			where:"SkillWhereInput",
			orderBy:"SkillOrderByInput",
			stage:"Stage",
			locales:"Locale"
		},
		skillVersion:{
			where:"VersionWhereInput"
		}
	},
	RGBAHue: `scalar.RGBAHue` as const,
	RGBAInput:{
		r:"RGBAHue",
		g:"RGBAHue",
		b:"RGBAHue",
		a:"RGBATransparency"
	},
	RGBATransparency: `scalar.RGBATransparency` as const,
	RichTextAST: `scalar.RichTextAST` as const,
	ScheduledOperation:{
		documentInStages:{
			stages:"Stage"
		},
		release:{
			locales:"Locale"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		affectedDocuments:{
			locales:"Locale"
		}
	},
	ScheduledOperationConnectInput:{
		where:"ScheduledOperationWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	ScheduledOperationCreateManyInlineInput:{
		connect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationCreateOneInlineInput:{
		connect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationManyWhereInput:{
		AND:"ScheduledOperationWhereInput",
		OR:"ScheduledOperationWhereInput",
		NOT:"ScheduledOperationWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		release:"ScheduledReleaseWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledOperationStatus",
		status_not:"ScheduledOperationStatus",
		status_in:"ScheduledOperationStatus",
		status_not_in:"ScheduledOperationStatus"
	},
	ScheduledOperationOrderByInput: "enum" as const,
	ScheduledOperationStatus: "enum" as const,
	ScheduledOperationUpdateManyInlineInput:{
		connect:"ScheduledOperationConnectInput",
		set:"ScheduledOperationWhereUniqueInput",
		disconnect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationUpdateOneInlineInput:{
		connect:"ScheduledOperationWhereUniqueInput"
	},
	ScheduledOperationWhereInput:{
		AND:"ScheduledOperationWhereInput",
		OR:"ScheduledOperationWhereInput",
		NOT:"ScheduledOperationWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		release:"ScheduledReleaseWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledOperationStatus",
		status_not:"ScheduledOperationStatus",
		status_in:"ScheduledOperationStatus",
		status_not_in:"ScheduledOperationStatus"
	},
	ScheduledOperationWhereUniqueInput:{

	},
	ScheduledRelease:{
		documentInStages:{
			stages:"Stage"
		},
		operations:{
			where:"ScheduledOperationWhereInput",
			orderBy:"ScheduledOperationOrderByInput",
			locales:"Locale"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		}
	},
	ScheduledReleaseConnectInput:{
		where:"ScheduledReleaseWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	ScheduledReleaseCreateInput:{
		releaseAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime"
	},
	ScheduledReleaseCreateManyInlineInput:{
		create:"ScheduledReleaseCreateInput",
		connect:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseCreateOneInlineInput:{
		create:"ScheduledReleaseCreateInput",
		connect:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseManyWhereInput:{
		AND:"ScheduledReleaseWhereInput",
		OR:"ScheduledReleaseWhereInput",
		NOT:"ScheduledReleaseWhereInput",
		releaseAt:"DateTime",
		releaseAt_not:"DateTime",
		releaseAt_in:"DateTime",
		releaseAt_not_in:"DateTime",
		releaseAt_lt:"DateTime",
		releaseAt_lte:"DateTime",
		releaseAt_gt:"DateTime",
		releaseAt_gte:"DateTime",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		operations_every:"ScheduledOperationWhereInput",
		operations_some:"ScheduledOperationWhereInput",
		operations_none:"ScheduledOperationWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledReleaseStatus",
		status_not:"ScheduledReleaseStatus",
		status_in:"ScheduledReleaseStatus",
		status_not_in:"ScheduledReleaseStatus"
	},
	ScheduledReleaseOrderByInput: "enum" as const,
	ScheduledReleaseStatus: "enum" as const,
	ScheduledReleaseUpdateInput:{
		releaseAt:"DateTime"
	},
	ScheduledReleaseUpdateManyInlineInput:{
		create:"ScheduledReleaseCreateInput",
		connect:"ScheduledReleaseConnectInput",
		set:"ScheduledReleaseWhereUniqueInput",
		update:"ScheduledReleaseUpdateWithNestedWhereUniqueInput",
		upsert:"ScheduledReleaseUpsertWithNestedWhereUniqueInput",
		disconnect:"ScheduledReleaseWhereUniqueInput",
		delete:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseUpdateManyInput:{
		releaseAt:"DateTime"
	},
	ScheduledReleaseUpdateManyWithNestedWhereInput:{
		where:"ScheduledReleaseWhereInput",
		data:"ScheduledReleaseUpdateManyInput"
	},
	ScheduledReleaseUpdateOneInlineInput:{
		create:"ScheduledReleaseCreateInput",
		update:"ScheduledReleaseUpdateWithNestedWhereUniqueInput",
		upsert:"ScheduledReleaseUpsertWithNestedWhereUniqueInput",
		connect:"ScheduledReleaseWhereUniqueInput"
	},
	ScheduledReleaseUpdateWithNestedWhereUniqueInput:{
		where:"ScheduledReleaseWhereUniqueInput",
		data:"ScheduledReleaseUpdateInput"
	},
	ScheduledReleaseUpsertInput:{
		create:"ScheduledReleaseCreateInput",
		update:"ScheduledReleaseUpdateInput"
	},
	ScheduledReleaseUpsertWithNestedWhereUniqueInput:{
		where:"ScheduledReleaseWhereUniqueInput",
		data:"ScheduledReleaseUpsertInput"
	},
	ScheduledReleaseWhereInput:{
		AND:"ScheduledReleaseWhereInput",
		OR:"ScheduledReleaseWhereInput",
		NOT:"ScheduledReleaseWhereInput",
		releaseAt:"DateTime",
		releaseAt_not:"DateTime",
		releaseAt_in:"DateTime",
		releaseAt_not_in:"DateTime",
		releaseAt_lt:"DateTime",
		releaseAt_lte:"DateTime",
		releaseAt_gt:"DateTime",
		releaseAt_gte:"DateTime",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		operations_every:"ScheduledOperationWhereInput",
		operations_some:"ScheduledOperationWhereInput",
		operations_none:"ScheduledOperationWhereInput",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		status:"ScheduledReleaseStatus",
		status_not:"ScheduledReleaseStatus",
		status_in:"ScheduledReleaseStatus",
		status_not_in:"ScheduledReleaseStatus"
	},
	ScheduledReleaseWhereUniqueInput:{

	},
	Skill:{
		documentInStages:{
			stages:"Stage"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		icon:{
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	SkillConnectInput:{
		where:"SkillWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	SkillCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		icon:"AssetCreateOneInlineInput"
	},
	SkillCreateManyInlineInput:{
		create:"SkillCreateInput",
		connect:"SkillWhereUniqueInput"
	},
	SkillCreateOneInlineInput:{
		create:"SkillCreateInput",
		connect:"SkillWhereUniqueInput"
	},
	SkillManyWhereInput:{
		AND:"SkillWhereInput",
		OR:"SkillWhereInput",
		NOT:"SkillWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		icon:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SkillOrderByInput: "enum" as const,
	SkillUpdateInput:{
		icon:"AssetUpdateOneInlineInput"
	},
	SkillUpdateManyInlineInput:{
		create:"SkillCreateInput",
		connect:"SkillConnectInput",
		set:"SkillWhereUniqueInput",
		update:"SkillUpdateWithNestedWhereUniqueInput",
		upsert:"SkillUpsertWithNestedWhereUniqueInput",
		disconnect:"SkillWhereUniqueInput",
		delete:"SkillWhereUniqueInput"
	},
	SkillUpdateManyInput:{

	},
	SkillUpdateManyWithNestedWhereInput:{
		where:"SkillWhereInput",
		data:"SkillUpdateManyInput"
	},
	SkillUpdateOneInlineInput:{
		create:"SkillCreateInput",
		update:"SkillUpdateWithNestedWhereUniqueInput",
		upsert:"SkillUpsertWithNestedWhereUniqueInput",
		connect:"SkillWhereUniqueInput"
	},
	SkillUpdateWithNestedWhereUniqueInput:{
		where:"SkillWhereUniqueInput",
		data:"SkillUpdateInput"
	},
	SkillUpsertInput:{
		create:"SkillCreateInput",
		update:"SkillUpdateInput"
	},
	SkillUpsertWithNestedWhereUniqueInput:{
		where:"SkillWhereUniqueInput",
		data:"SkillUpsertInput"
	},
	SkillWhereInput:{
		AND:"SkillWhereInput",
		OR:"SkillWhereInput",
		NOT:"SkillWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		icon:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SkillWhereUniqueInput:{

	},
	Social:{
		documentInStages:{
			stages:"Stage"
		},
		publishedBy:{
			locales:"Locale"
		},
		updatedBy:{
			locales:"Locale"
		},
		createdBy:{
			locales:"Locale"
		},
		image:{
			locales:"Locale"
		},
		scheduledIn:{
			where:"ScheduledOperationWhereInput",
			locales:"Locale"
		},
		history:{
			stageOverride:"Stage"
		}
	},
	SocialConnectInput:{
		where:"SocialWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	SocialCreateInput:{
		updatedAt:"DateTime",
		createdAt:"DateTime",
		color:"ColorInput",
		image:"AssetCreateOneInlineInput"
	},
	SocialCreateManyInlineInput:{
		create:"SocialCreateInput",
		connect:"SocialWhereUniqueInput"
	},
	SocialCreateOneInlineInput:{
		create:"SocialCreateInput",
		connect:"SocialWhereUniqueInput"
	},
	SocialManyWhereInput:{
		AND:"SocialWhereInput",
		OR:"SocialWhereInput",
		NOT:"SocialWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SocialOrderByInput: "enum" as const,
	SocialUpdateInput:{
		color:"ColorInput",
		image:"AssetUpdateOneInlineInput"
	},
	SocialUpdateManyInlineInput:{
		create:"SocialCreateInput",
		connect:"SocialConnectInput",
		set:"SocialWhereUniqueInput",
		update:"SocialUpdateWithNestedWhereUniqueInput",
		upsert:"SocialUpsertWithNestedWhereUniqueInput",
		disconnect:"SocialWhereUniqueInput",
		delete:"SocialWhereUniqueInput"
	},
	SocialUpdateManyInput:{
		color:"ColorInput"
	},
	SocialUpdateManyWithNestedWhereInput:{
		where:"SocialWhereInput",
		data:"SocialUpdateManyInput"
	},
	SocialUpdateOneInlineInput:{
		create:"SocialCreateInput",
		update:"SocialUpdateWithNestedWhereUniqueInput",
		upsert:"SocialUpsertWithNestedWhereUniqueInput",
		connect:"SocialWhereUniqueInput"
	},
	SocialUpdateWithNestedWhereUniqueInput:{
		where:"SocialWhereUniqueInput",
		data:"SocialUpdateInput"
	},
	SocialUpsertInput:{
		create:"SocialCreateInput",
		update:"SocialUpdateInput"
	},
	SocialUpsertWithNestedWhereUniqueInput:{
		where:"SocialWhereUniqueInput",
		data:"SocialUpsertInput"
	},
	SocialWhereInput:{
		AND:"SocialWhereInput",
		OR:"SocialWhereInput",
		NOT:"SocialWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		publishedBy:"UserWhereInput",
		updatedBy:"UserWhereInput",
		createdBy:"UserWhereInput",
		image:"AssetWhereInput",
		scheduledIn_every:"ScheduledOperationWhereInput",
		scheduledIn_some:"ScheduledOperationWhereInput",
		scheduledIn_none:"ScheduledOperationWhereInput"
	},
	SocialWhereUniqueInput:{

	},
	Stage: "enum" as const,
	SystemDateTimeFieldVariation: "enum" as const,
	UnpublishLocaleInput:{
		locale:"Locale",
		stages:"Stage"
	},
	User:{
		documentInStages:{
			stages:"Stage"
		}
	},
	UserConnectInput:{
		where:"UserWhereUniqueInput",
		position:"ConnectPositionInput"
	},
	UserCreateManyInlineInput:{
		connect:"UserWhereUniqueInput"
	},
	UserCreateOneInlineInput:{
		connect:"UserWhereUniqueInput"
	},
	UserKind: "enum" as const,
	UserManyWhereInput:{
		AND:"UserWhereInput",
		OR:"UserWhereInput",
		NOT:"UserWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		kind:"UserKind",
		kind_not:"UserKind",
		kind_in:"UserKind",
		kind_not_in:"UserKind"
	},
	UserOrderByInput: "enum" as const,
	UserUpdateManyInlineInput:{
		connect:"UserConnectInput",
		set:"UserWhereUniqueInput",
		disconnect:"UserWhereUniqueInput"
	},
	UserUpdateOneInlineInput:{
		connect:"UserWhereUniqueInput"
	},
	UserWhereInput:{
		AND:"UserWhereInput",
		OR:"UserWhereInput",
		NOT:"UserWhereInput",
		publishedAt:"DateTime",
		publishedAt_not:"DateTime",
		publishedAt_in:"DateTime",
		publishedAt_not_in:"DateTime",
		publishedAt_lt:"DateTime",
		publishedAt_lte:"DateTime",
		publishedAt_gt:"DateTime",
		publishedAt_gte:"DateTime",
		updatedAt:"DateTime",
		updatedAt_not:"DateTime",
		updatedAt_in:"DateTime",
		updatedAt_not_in:"DateTime",
		updatedAt_lt:"DateTime",
		updatedAt_lte:"DateTime",
		updatedAt_gt:"DateTime",
		updatedAt_gte:"DateTime",
		createdAt:"DateTime",
		createdAt_not:"DateTime",
		createdAt_in:"DateTime",
		createdAt_not_in:"DateTime",
		createdAt_lt:"DateTime",
		createdAt_lte:"DateTime",
		createdAt_gt:"DateTime",
		createdAt_gte:"DateTime",
		kind:"UserKind",
		kind_not:"UserKind",
		kind_in:"UserKind",
		kind_not_in:"UserKind"
	},
	UserWhereUniqueInput:{

	},
	VersionWhereInput:{
		stage:"Stage"
	},
	_FilterKind: "enum" as const,
	_MutationInputFieldKind: "enum" as const,
	_MutationKind: "enum" as const,
	_OrderDirection: "enum" as const,
	_RelationInputCardinality: "enum" as const,
	_RelationInputKind: "enum" as const,
	_RelationKind: "enum" as const,
	_SystemDateTimeFieldVariation: "enum" as const
}

export const ReturnTypes: Record<string,any> = {
	Aggregate:{
		count:"Int"
	},
	Asset:{
		stage:"Stage",
		locale:"Locale",
		localizations:"Asset",
		documentInStages:"Asset",
		mimeType:"String",
		size:"Float",
		width:"Float",
		height:"Float",
		fileName:"String",
		handle:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		imageProject:"Project",
		imageSocial:"Social",
		imagePageMetadata:"PageMetadata",
		iconSkill:"Skill",
		scheduledIn:"ScheduledOperation",
		history:"Version",
		url:"String"
	},
	AssetConnection:{
		pageInfo:"PageInfo",
		edges:"AssetEdge",
		aggregate:"Aggregate"
	},
	AssetEdge:{
		node:"Asset",
		cursor:"String"
	},
	BatchPayload:{
		count:"Long"
	},
	Color:{
		hex:"Hex",
		rgba:"RGBA",
		css:"String"
	},
	Date: `scalar.Date` as const,
	DateTime: `scalar.DateTime` as const,
	DocumentVersion:{
		id:"ID",
		stage:"Stage",
		revision:"Int",
		createdAt:"DateTime",
		data:"Json"
	},
	Hex: `scalar.Hex` as const,
	Json: `scalar.Json` as const,
	Location:{
		latitude:"Float",
		longitude:"Float",
		distance:"Float"
	},
	Long: `scalar.Long` as const,
	Mutation:{
		createAsset:"Asset",
		updateAsset:"Asset",
		deleteAsset:"Asset",
		upsertAsset:"Asset",
		publishAsset:"Asset",
		unpublishAsset:"Asset",
		updateManyAssetsConnection:"AssetConnection",
		deleteManyAssetsConnection:"AssetConnection",
		publishManyAssetsConnection:"AssetConnection",
		unpublishManyAssetsConnection:"AssetConnection",
		updateManyAssets:"BatchPayload",
		deleteManyAssets:"BatchPayload",
		publishManyAssets:"BatchPayload",
		unpublishManyAssets:"BatchPayload",
		schedulePublishAsset:"Asset",
		scheduleUnpublishAsset:"Asset",
		deleteScheduledOperation:"ScheduledOperation",
		createScheduledRelease:"ScheduledRelease",
		updateScheduledRelease:"ScheduledRelease",
		deleteScheduledRelease:"ScheduledRelease",
		createProject:"Project",
		updateProject:"Project",
		deleteProject:"Project",
		upsertProject:"Project",
		publishProject:"Project",
		unpublishProject:"Project",
		updateManyProjectsConnection:"ProjectConnection",
		deleteManyProjectsConnection:"ProjectConnection",
		publishManyProjectsConnection:"ProjectConnection",
		unpublishManyProjectsConnection:"ProjectConnection",
		updateManyProjects:"BatchPayload",
		deleteManyProjects:"BatchPayload",
		publishManyProjects:"BatchPayload",
		unpublishManyProjects:"BatchPayload",
		schedulePublishProject:"Project",
		scheduleUnpublishProject:"Project",
		createSocial:"Social",
		updateSocial:"Social",
		deleteSocial:"Social",
		upsertSocial:"Social",
		publishSocial:"Social",
		unpublishSocial:"Social",
		updateManySocialsConnection:"SocialConnection",
		deleteManySocialsConnection:"SocialConnection",
		publishManySocialsConnection:"SocialConnection",
		unpublishManySocialsConnection:"SocialConnection",
		updateManySocials:"BatchPayload",
		deleteManySocials:"BatchPayload",
		publishManySocials:"BatchPayload",
		unpublishManySocials:"BatchPayload",
		schedulePublishSocial:"Social",
		scheduleUnpublishSocial:"Social",
		createPageMetadata:"PageMetadata",
		updatePageMetadata:"PageMetadata",
		deletePageMetadata:"PageMetadata",
		upsertPageMetadata:"PageMetadata",
		publishPageMetadata:"PageMetadata",
		unpublishPageMetadata:"PageMetadata",
		updateManyPagesMetadataConnection:"PageMetadataConnection",
		deleteManyPagesMetadataConnection:"PageMetadataConnection",
		publishManyPagesMetadataConnection:"PageMetadataConnection",
		unpublishManyPagesMetadataConnection:"PageMetadataConnection",
		updateManyPagesMetadata:"BatchPayload",
		deleteManyPagesMetadata:"BatchPayload",
		publishManyPagesMetadata:"BatchPayload",
		unpublishManyPagesMetadata:"BatchPayload",
		schedulePublishPageMetadata:"PageMetadata",
		scheduleUnpublishPageMetadata:"PageMetadata",
		createSkill:"Skill",
		updateSkill:"Skill",
		deleteSkill:"Skill",
		upsertSkill:"Skill",
		publishSkill:"Skill",
		unpublishSkill:"Skill",
		updateManySkillsConnection:"SkillConnection",
		deleteManySkillsConnection:"SkillConnection",
		publishManySkillsConnection:"SkillConnection",
		unpublishManySkillsConnection:"SkillConnection",
		updateManySkills:"BatchPayload",
		deleteManySkills:"BatchPayload",
		publishManySkills:"BatchPayload",
		unpublishManySkills:"BatchPayload",
		schedulePublishSkill:"Skill",
		scheduleUnpublishSkill:"Skill"
	},
	Node:{
		"...on Asset": "Asset",
		"...on PageMetadata": "PageMetadata",
		"...on Project": "Project",
		"...on ScheduledOperation": "ScheduledOperation",
		"...on ScheduledRelease": "ScheduledRelease",
		"...on Skill": "Skill",
		"...on Social": "Social",
		"...on User": "User",
		id:"ID",
		stage:"Stage"
	},
	PageInfo:{
		hasNextPage:"Boolean",
		hasPreviousPage:"Boolean",
		startCursor:"String",
		endCursor:"String",
		pageSize:"Int"
	},
	PageMetadata:{
		stage:"Stage",
		documentInStages:"PageMetadata",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		title:"String",
		summary:"String",
		slug:"String",
		pageNumber:"Int",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		image:"Asset",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	PageMetadataConnection:{
		pageInfo:"PageInfo",
		edges:"PageMetadataEdge",
		aggregate:"Aggregate"
	},
	PageMetadataEdge:{
		node:"PageMetadata",
		cursor:"String"
	},
	Project:{
		stage:"Stage",
		documentInStages:"Project",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		name:"String",
		slug:"String",
		description:"String",
		tags:"String",
		demo:"String",
		sourceCode:"String",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		image:"Asset",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	ProjectConnection:{
		pageInfo:"PageInfo",
		edges:"ProjectEdge",
		aggregate:"Aggregate"
	},
	ProjectEdge:{
		node:"Project",
		cursor:"String"
	},
	Query:{
		node:"Node",
		users:"User",
		user:"User",
		usersConnection:"UserConnection",
		assets:"Asset",
		asset:"Asset",
		assetsConnection:"AssetConnection",
		assetVersion:"DocumentVersion",
		scheduledOperations:"ScheduledOperation",
		scheduledOperation:"ScheduledOperation",
		scheduledOperationsConnection:"ScheduledOperationConnection",
		scheduledReleases:"ScheduledRelease",
		scheduledRelease:"ScheduledRelease",
		scheduledReleasesConnection:"ScheduledReleaseConnection",
		projects:"Project",
		project:"Project",
		projectsConnection:"ProjectConnection",
		projectVersion:"DocumentVersion",
		socials:"Social",
		social:"Social",
		socialsConnection:"SocialConnection",
		socialVersion:"DocumentVersion",
		pagesMetadata:"PageMetadata",
		pageMetadata:"PageMetadata",
		pagesMetadataConnection:"PageMetadataConnection",
		pageMetadataVersion:"DocumentVersion",
		skills:"Skill",
		skill:"Skill",
		skillsConnection:"SkillConnection",
		skillVersion:"DocumentVersion"
	},
	RGBA:{
		r:"RGBAHue",
		g:"RGBAHue",
		b:"RGBAHue",
		a:"RGBATransparency"
	},
	RGBAHue: `scalar.RGBAHue` as const,
	RGBATransparency: `scalar.RGBATransparency` as const,
	RichText:{
		raw:"RichTextAST",
		html:"String",
		markdown:"String",
		text:"String"
	},
	RichTextAST: `scalar.RichTextAST` as const,
	ScheduledOperation:{
		stage:"Stage",
		documentInStages:"ScheduledOperation",
		rawPayload:"Json",
		errorMessage:"String",
		description:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		release:"ScheduledRelease",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		status:"ScheduledOperationStatus",
		affectedDocuments:"ScheduledOperationAffectedDocument"
	},
	ScheduledOperationAffectedDocument:{
		"...on Asset":"Asset",
		"...on PageMetadata":"PageMetadata",
		"...on Project":"Project",
		"...on Skill":"Skill",
		"...on Social":"Social"
	},
	ScheduledOperationConnection:{
		pageInfo:"PageInfo",
		edges:"ScheduledOperationEdge",
		aggregate:"Aggregate"
	},
	ScheduledOperationEdge:{
		node:"ScheduledOperation",
		cursor:"String"
	},
	ScheduledRelease:{
		stage:"Stage",
		documentInStages:"ScheduledRelease",
		releaseAt:"DateTime",
		isImplicit:"Boolean",
		isActive:"Boolean",
		errorMessage:"String",
		description:"String",
		title:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		operations:"ScheduledOperation",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		status:"ScheduledReleaseStatus"
	},
	ScheduledReleaseConnection:{
		pageInfo:"PageInfo",
		edges:"ScheduledReleaseEdge",
		aggregate:"Aggregate"
	},
	ScheduledReleaseEdge:{
		node:"ScheduledRelease",
		cursor:"String"
	},
	Skill:{
		stage:"Stage",
		documentInStages:"Skill",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		name:"String",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		icon:"Asset",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	SkillConnection:{
		pageInfo:"PageInfo",
		edges:"SkillEdge",
		aggregate:"Aggregate"
	},
	SkillEdge:{
		node:"Skill",
		cursor:"String"
	},
	Social:{
		stage:"Stage",
		documentInStages:"Social",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		name:"String",
		url:"String",
		color:"Color",
		publishedBy:"User",
		updatedBy:"User",
		createdBy:"User",
		image:"Asset",
		scheduledIn:"ScheduledOperation",
		history:"Version"
	},
	SocialConnection:{
		pageInfo:"PageInfo",
		edges:"SocialEdge",
		aggregate:"Aggregate"
	},
	SocialEdge:{
		node:"Social",
		cursor:"String"
	},
	User:{
		stage:"Stage",
		documentInStages:"User",
		isActive:"Boolean",
		picture:"String",
		name:"String",
		publishedAt:"DateTime",
		updatedAt:"DateTime",
		createdAt:"DateTime",
		id:"ID",
		kind:"UserKind"
	},
	UserConnection:{
		pageInfo:"PageInfo",
		edges:"UserEdge",
		aggregate:"Aggregate"
	},
	UserEdge:{
		node:"User",
		cursor:"String"
	},
	Version:{
		id:"ID",
		stage:"Stage",
		revision:"Int",
		createdAt:"DateTime"
	}
}

export const Ops = {
mutation: "Mutation" as const,
	query: "Query" as const
}